### ISSUE TITLE
Missing informations when StorageException is in the InnerException of an other exception.

### ISSUE THREAD

**Issue by Trysior** [Azure/azure-storage-net#118]
When you do .ToString() directly on a StorageException the RequestInformation (ErrorCode by example) are in the generated string. But when you wrap this exception into another (InnerException) and you do .ToString() on this one this very usefull informations is lost. That's because the .ToString() of the base class Exception call the Message property of every InnerException and does not call .ToString().

In StorageException the .ToString() is override but the Message is not and the information of the RequestInformation are never added to the Message.

That make logging understanding harder when an application call a Library that wrap StorageException into an other Exception.

**Comment by veena-udayabhanu** [comment]
This is a regression in .NET 4.0 and exists in the current stable release (4.5.2). Please see https://connect.microsoft.com/VisualStudio/feedback/details/586619/exception-tostring-no-longer-calls-overridable-tostring-for-innerexception for further details. Until that issue is resolved, you can work around by explicitly calling ToString() on the inner StorageException in your application.
