### ISSUE TITLE
404 exceptions when an entity is not found

### ISSUE THREAD

**Issue by praneetloke** [Azure/azure-storage-net#119]
We have app insights reporting against our application, this includes tracking calls made to dependent resources, like Table Storage in this case. We make several million calls to Table Storage *every day* and for *every* single call that we make to table storage to get an entity and it can't find it, which is fine, results in a `WebException` from `System.Net.HttpWebRequest.GetResponse`. I understand that a REST API is supposed to return a 404 status code when a requested object isn't found and hence the table service returning the 404 makes sense. Surely, something can be done to prevent the exception from being thrown by `System.Net`, from inside your client code when you try and access the response? As you can imagine, so many 404 Not Found exceptions skews app insights metrics about our application and that makes everyone nervous. We are having to spend time digging through false positives and several of them.

I came across [this](http://web.archive.org/web/20140111052656/http://fearthecowboy.com/2011/09/02/fixing-webrequests-desire-to-throw-exceptions-instead-of-returning-status/) article describing a way to handle this. Perhaps, this could give an idea of how you would like to handle this.

**Comment by pemari-msft** [comment]
In our convenience layer, we wrap all exceptions that result from an HttpWebRequest service call in our StorageException class to make them easy to catch. We return a StorageException for all such error paths, including 404.  We can consider alternatives or workarounds in upcoming releases, but the HTTPWebRequest paradigm expects exceptions to be thrown as a control flow mechanism when status codes are outside of the successful 200s, so our default behavior is likely to remain in the same vein. The article recommends swallowing the exception and returning a status code to the caller, which would not solve the underlying problem – the exception would still get thrown, just caught inside our API rather than in your calling code, right?

**Comment by pemari-msft** [comment]
Hi, please feel free to reopen this if you'd like to have further discussion about the HTTPWebRequest paradigm or how your scenario operates. We'd love to hear your feedback!
