### ISSUE TITLE
WindowsAzure.Storage 4.4-preview for Xamarin is missing SAS methods.

### ISSUE THREAD

**Issue by pierceboggan** [Azure/azure-storage-net#134]
The [Getting Started with Azure Storage on Xamarin](http://blogs.msdn.com/b/windowsazurestorage/archive/2015/04/29/getting-started-with-azure-storage-on-xamarin.aspx) tutorial recommends using the [.NET method for generating a SAS](http://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-shared-access-signature-part-2/). However, many (if not all) of the methods for handling this are not available in the 4.4 preview of Azure Storage (targeting Xamarin).

Specifically, the "Generate a Shared Access Signature URI for a Container" and "Create a Stored Access Policy on the Container" portions of the tutorial mention a few specific methods that I have been unable to use:
* `string sasContainerToken = container.GetSharedAccessSignature(sasConstraints);`
* `string sasBlobToken = blob.GetSharedAccessSignature(sasConstraints);`

I realize this is a preview and everything may not be implemented, and I'm very grateful that you guys released Azure Storage for Xamarin (perfect timing!). I just wanted to make sure you were aware of this, and, if so, wanted to get an idea of when we can expect this feature to be working with Xamarin. :+1:

**Comment by Cheesebaron** [comment]
On the other hand I can confirm that the PCL version can consume SAS tokens. What we usually do in our environment is that the Server side handles all the creation of SAS tokens and passes them to the Clients, but your situation might be different.

**Comment by pemari-msft** [comment]
Hi Pierce,
Yes, as Tomasz mentioned, you should never have your storage account key in a client side app. Because of this, we have only included the methods that consume SAS tokens, and not those that produce them. The Getting Started recommends using Azure Powershell commands or to implement a server-side SAS token generator/ , like in Tomasz’ scenario. 

Would you mind sharing your scenario a bit more for our understanding? Does this address your concerns? 

We are also currently in the process of expanding our Shared Access Signature support (read more about that here: http://blogs.msdn.com/b/windowsazurestorage/archive/2015/04/29/build-2015-azure-storage-announcements.aspx), and the methods to consume those improvements will be added to this library in an upcoming release as well.


Thanks,
Peter

**Comment by pemari-msft** [comment]
Closed for nonresponse -- please feel free to reopen if you have more details about your scenario and any missing functionality. Thanks!
