### ISSUE TITLE
DNX library still based on WinRT

### ISSUE THREAD

**Issue by markrendle** [Azure/azure-storage-net#140]
Following up on #130 

The specific issue about StorageException being internal has been resolved, but the DNX package is still being built from the **WindowsRuntime** sources instead of the **ClassLibraryCommon** sources. This means that huge chunks of the SDK are missing (e.g. the whole of Analytics).

Is there (still) any reason why the DNX library needs to be based on WinRT as opposed to the full code?

**Comment by markrendle** [comment]
Oh, argh. This is so frustrating.

I've been busy building the `preview` branch on my Linux box, and by setting the `WINDOWS_DESKTOP`, `SYNC` and `TASK` compiler flags, and removing `ASPNET_K`, plus updating the sources to point at `ClassLibraryCommon` and `WindowsDesktop` sources, I've got everything building quite happily against Mono (4.3), but Core is a total disaster.

I've dumped the `dnu build` output in [this gist](https://gist.github.com/markrendle/4bcc676d779349389692) for reference.

Obviously there are still a bunch of things missing from CoreFx, such as [System.Net.Requests](https://github.com/dotnet/corefx-progress/blob/master/src-diff/System.Net.Requests.md), which the main sources here rely on.

**Proposed stop-gap solution:**
Is there any possibility of creating completely separate projects for dnx451 and dnxcore50 so that people using a full CLR (either .NET or Mono) can access the full functionality of the SDK?

**Comment by pemari-msft** [comment]
Hi Mark, 

Thanks for your interest in our library targeting DNX. Currently, our DNX support is in preview, but we are definitely working to improve the functionality. The reasoning behind the decision to build the DNX package from the WindowsRuntime sources is because the entirety of the underlying HTTP stack (among other things) from the ClassLibraryCommon sources is not supported by DNX core. It would not be feasible to build the DNX core library from the ClassLibraryCommon sources for that reason -- as you've found from your current experiments. We felt that having a unified experience between DNX and DNX core was important -- building the two targets from different sources would feel rather inconsistent and would be more difficult to use and maintain. We'll take it as a request, however, and will evaluate it as an approach moving forward.

For the given example of Analytics, there is no async support in the WinRT library, which is the limiting factor in why it was not included in WinRT, which is entirely async. We will certainly take it as a feature request to implement AnalyticsClient specifically for the DNX target.

Would you mind sharing what other functionality you need for your scenario that is missing from our DNX library? We can try to prioritize those features as we move forward.
Again, thanks for your feedback! 

Best,
Peter

**Comment by markrendle** [comment]
Hi Peter,

Thanks for taking the time to give such a comprehensive answer, I really appreciate it.

My scenario is that I have a full-blown Storage-focused application that I am porting to ASP.NET 5 and MVC 6 with the intention of hosting it in Docker on Linux. So ideally I need every feature of Azure Storage surfaced in the DNX profile of the SDK. I realise that I am an edge case, and for the time being I am both willing and able to simply use a fork of this repo and hack together a version of the full profile to work with DNX+Mono.

I'll continue to track the progress of the CoreFx project and when it reaches a stage where my fork of this repo builds happily against that I'll be sure to let you guys know :)

Cheers,
Mark
