### ISSUE TITLE
Add ability to use own MD5 sum in PCL

### ISSUE THREAD

**Issue by Cheesebaron** [Azure/azure-storage-net#141]
When uploading a `CloudBlockBlob` and you pass a `BlobRequestOptions` with `StoreBlobContentMD5` set to `true`, then you will get a nice exception telling you that MD5 is not supported in PCL.

Lets say I have my own way of calculating this MD5 sum, and I still want it to be stored, why is it that I cannot pass it somewhere?

Or rather, why is it that MD5 sums, which are pretty simple to calculate are not present in PCL?

**Comment by pemari-msft** [comment]
Hi Tomasz,

Thanks for the feedback. You’re right that we should allow an MD5 to be stored even if not supported via StoreBlobContentMD5. We will look to correct this in a future release.  
The reason MD5 is not supported in our PCL  preview is because it is platform specific in implementation. This is why we also do not have MD5 support in our .NET Windows Phone library.

Best,
Peter

**Comment by pemari-msft** [comment]
New Xamarin library using NETCore has fixed all our MD5 problems :D Please take a look at 7.2.0.
