### ISSUE TITLE
Version of dependency Microsoft.WindowsAzure.ConfigurationManager

### ISSUE THREAD

**Issue by siroky** [Azure/azure-storage-net#143]
Hi, when I add the latest stable `WindowsAzure.Storage 4.3.0` to my project, it causes a conflict on the dependency `Microsoft.WindowsAzure.ConfigurationManager >= 1.8.0` because I have another package `logentries.core 2.6.10` that also depends on the `Microsoft.WindowsAzure.ConfigurationManager >= 3.1.0`.

Why does `WindowsAzure.Storage 4.3.0` depend on that old version of ConfigurationManager when there are already two newer major versions?  I guess the versions `1.8.0` and `3.1.0` aren't compatible which forces us to use old version of `logentries.core` that depends on `Microsoft.WindowsAzure.ConfigurationManager >= 2.0.1`.

**Comment by pemari-msft** [comment]
Thanks for bringing this to our attention. We'll look to correct this in an upcoming release.

**Comment by pemari-msft** [comment]
Hi @siroky , we removed the dependency on ConfigurationManager in our 5.0.0 release which can be found on nuget. Thanks again for your feedback.

**Comment by siroky** [comment]
Great, thanks!

**Comment by babelshift** [comment]
After updating to 5.0.0, my project would not compile because the removed namespace was no longer available. In order to resolve this, I had to manually install Windows Azure Storage Configuration Manager package from NuGet. Just a reference for anyone else who runs in to this.

**Comment by pemari-msft** [comment]
Hi @babelshift , can you please clarify what you mean? 

Why did the project not compile? Did you have a dependency on ConfigurationManager yourself? We removed the references to ConfigurationManager in our own project so you should not have had issues compiling.

Thanks!

**Comment by babelshift** [comment]
After some more testing, I have a better description.

I installed WindowsAzure.Storage 4.3.0 from NuGet. This included the following references in my project:
* Microsoft.WindowsAzure.Storage 4.3.0.0
* Microsoft.WindowsAzure.Configuration 1.8.0.0

Then I updated to WindowsAzure.Storage 5.0.0 from NuGet. My references were updated as follows:
* Microsoft.WindowsAzure.Storage 5.0.0.0

Since my project had a dependency on Microsoft.WindowsAzure.Configuration, I needed to install the latest version from NuGet since it appears the WindowsAzure.Storage package no longer includes the reference.

**Comment by pemari-msft** [comment]
Interesting. We shouldn't need the reference to Configuration at all anymore. I'm going to try to repro, thanks for the added details.

**Comment by pemari-msft** [comment]
When I updated from 4.3.0 to 5.0.0 in a local console app project, Visual Studio automatically removed the reference to Configuration Manager. Perhaps you had added the reference to ConfigurationManager manually. We no longer have this dependency, so you should be able to remove it yourself now. Sorry for the inconvenience.

**Comment by babelshift** [comment]
Hi Peter. Thanks for the quick feedback. The scenario you describe is the problem that I faced.

The 4.3.0 package includes a ConfigurationManager reference with it while the 5.0.0 package does not. If anyone is depending on its existence (such as using CloudConfigurationManager class), then upgrading to 5.0.0 is going to break the project since it removes that reference. That's what happened to me.

It isn't a huge deal since it's easy enough to add the reference back by searching for the ConfigurationManager separate package in NuGet.

**Comment by pemari-msft** [comment]
Great, thanks!
