### ISSUE TITLE
CloudBlockBlob.DownloadToStreamAsync docs are incomplete

### ISSUE THREAD

**Issue by mjrousos** [Azure/azure-storage-net#145]
The MSDN documentation for various overloads of [CloudBlockBlob.DownloadToStreamAsync](https://msdn.microsoft.com/en-us/library/azure/microsoft.windowsazure.storage.blob.cloudblockblob.downloadtostreamasync.aspx) is very sparse on information. 

Specifically lacking is the set of exceptions that may be thrown. DownloadToStreamAsync can throw a StorageException if the operation times out (which can occur when downloading multiple streams concurrently), but the documentation doesn't mention this possibility or how to address it.

It would be helpful to document:

1. The exceptions that can be thrown by DownloadToStreamAsync (and in what scenarios)
2. In DownloadToStreamAsync(Stream)'s documentation, a remark that the other overloads accepting a BlobRequestOptions argument can be used to modify timeout and retry behaviors to avoid some timeouts.

**Comment by jehine-MSFT** [comment]
Hello @mjrousos,

Thank you for the suggestion! We generate our docs from code so they may not have complete usage information. To help users become familiar with how our library works we updated our Getting Started docs in the README for the next release.

As for understanding overloads, it should be clear from intellisense and the docs that there are multiple overloads for each APIs. At this time we don’t want to list all possible exceptions for each APIs since they happen for a multitude of reasons. 

Thanks again for the feedback!
