### ISSUE TITLE
Assembly File Version mismatch in 5.0.1-preview nuget

### ISSUE THREAD

**Issue by Cheesebaron** [Azure/azure-storage-net#166]
Looking at the file assembly version for the Windows.Azure.Storage assembly in the win8 folder it says 5.0.0, while the one in the portable folder reports 5.0.1.

**Comment by pemari-msft** [comment]
Yes, this is entirely intentional. The preview targets (Portable, DNX 4.5.1, CoreCLR 5.0) are in the 5.0.1-preview version of the library. This preview library package also includes the GA targets from the 5.0.0 library for convenience.

In other words, the win8, wp8, net40, and wpa dlls are identical in the 5.0.0 and 5.0.1-preview versions of the library, and are GA. The assembly versions are the same to reflect that.

**Comment by Cheesebaron** [comment]
I still believe this is an issue. Take this example:

You have a PCL where the PCL version of the library is added. Current version for that is 5.0.3-preview, assembly version 5.0.3.0.
You reference this PCL in your Application project, lets say this is a Windows 8.1 app. Now you want to use something from this library in the Application project and you want to add a reference to it. You add the nuget and it pulls in 5.0.3-preview, but the actual assembly is version 5.0.2.0.

Now when you launch your application, it blows up because it cannot find version 5.0.3.0 of the library. So until I solve the mismatch it will keep throwing an exception when loading.

Is this really as intended?

**Comment by pemari-msft** [comment]
This could be fixed rather easily with binding redirects, I imagine, but I agree it's not particularly user friendly. Because of this, I've changed how we've done 6.0.0 and 6.0.1-preview so they have the corresponding assembly versions in each package. Thanks for the feedback.
