### ISSUE TITLE
Microsoft.WindowsAzure.Storage.xml contains hexadecimal (?) data

### ISSUE THREAD

**Issue by EnCey** [Azure/azure-storage-net#189]
I noticed that XML documentation (intellisense) was missing for all Storage API methods and in an attempt to figure out why, I realized that the `Microsoft.WindowsAzure.Storage.xml` that comes with the NuGet package contains what appears to be hexadecimal data:

```
4d69 6372 6f73 6f66 7420 432f 432b 2b20
4d53 4620 372e 3030 0d0a 1a44 5300 0000
0002 0000 0200 0000 f310 0000 744e 0000
0000 0000 f210 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
[...]
```
Unless this is some freaky kind of encoding, I guess there is a problem with the build or NuGet packaging? 

*Update:* I converted the first few lines to ASCII and got `Microsoft C/C++ MSF 7.00` – I then noticed that `Microsoft.WindowsAzure.Storage.xml` has the exact same file size as `Microsoft.WindowsAzure.Storage.pdb`, so I guess mystery solved?

**Comment by pemari-msft** [comment]
Thanks for reporting this. Yes, there was an error in our packaging -- unfortunately our pdbs were included twice instead of the xml.

I've fixed the issue going forward. The Storage Client Library API reference docs are current: https://msdn.microsoft.com/en-us/library/azure/dn261237.aspx but we'll look to find a way to fix this as well.

**Comment by EnCey** [comment]
Thanks. I just built the source myself and pasted the xml over that in the NuGet package as a workaround, in case someone else is looking for an interim solution.
