### ISSUE TITLE
Port Exhaustion

### ISSUE THREAD

**Issue by chris02031** [Azure/azure-storage-net#197]
EDIT: Running the code on my home system I do not get the same issue. Connections are correctly changing to TIME_WAIT in netstat after hitting the database. So, this may be an azure VM issue? Any thoughts still much appreciated.

I'm running the latest version of the WindowsAzure.Storage library, 6.1.1 in .Net 5.0 (x64 DNX)

This was previously a known issue but is supposed to have been fixed back in .NET 4.5.1. It's exactly the issue I'm having. http://blogs.msdn.com/b/windowsazurestorage/archive/2013/08/08/net-clients-encountering-port-exhaustion-after-installing-kb2750149-or-kb2805227.aspx

I'm hitting a table in Azure Storage with 100m+ rows to insert. I've focused on making the code fast and scalable, it maxes out an Azure D12 VM running Datacenter 2012 R2. I'm seeing 5,000 - 10,000 entities processed per second (read file, process, upload).

The process always crashes out at ~16,384 batches (around 320,000 records) with a classic port exhaustion error: Only one usage of each socket address (protocol/network address/port) is normally permitted.

I've done the usual things: increase MaxUserPort (64434) and decreased TcpTimedWaitDelay (15 seconds). MaxUserPort seems to be ignored given the suspiciously logical 16,384 it fails at.

Netstat shows that the ports are never being closed in the first place. The state on all of them remains 'Established' untill the process itself is closed, then they switch to 'Time-wait' before dropping off.

The actual connection code comes down to:

var acx = CloudStorageAccount.Parse(conn);
var client = acx.CreateCloudTableClient();
var table = client.GetTableReference("Test");
var op = new TableBatchOperation();

foreach (var record in batch) //Batch is just a bunch of entity objects
    op.InsertOrReplace(record);

try
{
    await table.ExecuteBatchAsync(op, opsConfig, null);
    Interlocked.Add(ref totalUploaded, batch.Count);
}
catch...

I've tried every variation I can think of - reusing a pool of TableBatchOperations, having a single table/client/account to creating an object for every hit, and every combination in between.

The problem seems to be lower level than I can get to. When the issue was supposedly fixed two years ago the connections were staying open because the response stream wasn't being read properly.

Grateful for any suggestions! Please just ask if you need more information or clarification.

**Comment by jasonnewyork** [comment]
We will take a look and get back to you Chris.

Sent from my Windows Phone
________________________________

**Comment by chris02031** [comment]
Appreciate it - thanks.

**Comment by jasonnewyork** [comment]
Btw, I am interested in your scenario can you share more details?

Sent from my Windows Phone

-----Original Message-----
From: "Jason Hogg" <jasonnewyork@hotmail.com>
Sent: ‎11/‎7/‎2015 8:42 AM
To: "Azure/azure-storage-net" <reply@reply.github.com>; "Azure/azure-storage-net" <azure-storage-net@noreply.github.com>
Subject: RE: [azure-storage-net] Port Exhaustion (#197)

We will take a look and get back to you Chris.

Sent from my Windows Phone


From: chris02031
Sent: ‎11/‎7/‎2015 8:33 AM
To: Azure/azure-storage-net
Subject: [azure-storage-net] Port Exhaustion (#197)


I'm running the latest version of the WindowsAzure.Storage library, 6.1.1. This was previously a known issue but is supposed to have been fixed back in .NET 4.5.1. It's exactly the issue I'm having.
http://blogs.msdn.com/b/windowsazurestorage/archive/2013/08/08/net-clients-encountering-port-exhaustion-after-installing-kb2750149-or-kb2805227.aspx
I'm hitting a table in Azure Storage with 100m+ rows to insert. I've focused on making the code fast and scalable, it maxes out an Azure D12 VM running Datacenter 2012 R2. I'm seeing 5,000 - 10,000 entities processed per second (read file, process, upload).
The process always crashes out at ~16,384 batches (around 320,000 records) with a classic port exhaustion error: Only one usage of each socket address (protocol/network address/port) is normally permitted.
I've done the usual things: increase MaxUserPort (64434) and decreased TcpTimedWaitDelay (15 seconds). MaxUserPort seems to be ignored given the suspiciously logical 16,384 it fails at.
Netstat shows that the ports are never being closed in the first place. The state on all of them remains 'Established' untill the process itself is closed, then they disappear.
The actual connection code comes down to:
var acx = CloudStorageAccount.Parse(conn);
var client = acx.CreateCloudTableClient();
var table = client.GetTableReference("Test");
var op = new TableBatchOperation();
foreach (var record in batch) //Batch is just a bunch of entity objects
op.InsertOrReplace(record);
try
{
await table.ExecuteBatchAsync(op, opsConfig, null);
Interlocked.Add(ref totalUploaded, batch.Count);
}
catch...
I've tried every variation I can think of - reusing a pool of TableBatchOperations, having a single table/client/account to creating an object for every hit, and every combination in between.
The problem seems to be lower level than I can get to. When the issue was supposedly fixed two years ago the connections were staying open because the response stream wasn't being read properly.
Grateful for any suggestions! Please just ask if you need more information or clarification.

**Comment by chris02031** [comment]
I've just added an edit - I do not see the same issue on my home system (connections do get closed) which suggests a configuration issue or Azure VM issue rather than the library. Still struggling to pin this one down though.

I've got a large CSV file - this contains about 30m records, representing every address in the UK. It's read in batches of 20k lines and each batch is then parsed with three entities created. The variants are just denormalization, same object different keys. Objects are grouped by their PK, and each group correlates to the 'batch' variable in the code extract in the original post. 

The PK-grouped entities are processed by a series of tasks. A task attempts to acquire a batch of entities from the queue. If successful it enters the code in the original post.

**Comment by chris02031** [comment]
Poking around in the source code I'm thinking an explicit call to HttpClient.Dispose() may do the trick, though I know it isn't the typical approach with HttpClient. 

I'm trying to compile the source but am struggling to produce a library for .NET Core.

Using VS 2015, targeting ASP.NET Core 5.0 in the portable library, under NuGet add Microsoft.NETCore - but later there's a conflict and I can't restore Microsoft.Data.Edm or Microsoft.Data.OData... I don't know how you guys do it.

I'm at a loss as to why Azure is different and no suggestions on the Azure forums.

**Comment by jasonnewyork** [comment]
Odd I was able to get the portable library to build. Have you tried removing Microsoft.Data.Edm and Microsoft.Data.OData and then adding them again from Nuget package manager?

Date: Sat, 7 Nov 2015 15:15:22 -0800

**Comment by chris02031** [comment]
What version of VS are you using?

On VS 2015, 'out of the box' I can build the source, but it doesn't target .NET core. Trying to do so errors with 'The selection does not share any portable APIs'. The only workable combination I can get is .NET Core and .NET 4.6, with none of the Xamarin options, and going down that route ultimately gave rise to the compatibility errors on the Edm and OData libraries (NuGet won't allow them to be added).

![cant target core](https://cloud.githubusercontent.com/assets/15705822/11020725/642f848c-8620-11e5-80bb-2051bbcbf1ab.jpg)

**Comment by jasonnewyork** [comment]
We have a coreclr lib which is different to the portable one. I haven't built for coreclr so will get more info from Peter later today or tomorrow...

Sent from my Windows Phone
________________________________

**Comment by chris02031** [comment]
Thanks for the clarification.

**Comment by pemari-msft** [comment]
Hi Chris, 

Sorry for the delay as I was out of contact. So at this point, you're thinking there's some sort of Azure VM issue that is causing ports to be held open leading to port exhaustion when using our library. It sounds like perhaps this might not be due to the library, so perhaps we should be trying to repro the issue just via HttpClient. 

To be clear, this is a bit different from that linked `known issue` because that was for HttpWebRequest, not HttpClient. 

I see you're trying to get our DNX code compiling, however, you may be using our PCL in order to do so. Our project file for CoreCLR is located in the [AspNet folder](https://github.com/Azure/azure-storage-net/blob/master/Lib/AspNet/Microsoft.WindowsAzure.Storage/Microsoft.WindowsAzure.Storage.xproj).
Please let us know if you find any issues compiling with the project.json located there. 

Thanks,
Peter

**Comment by chris02031** [comment]
Hi Peter,

Thanks for following up. I agree that it would be sensible to try and pin down whether this is an issue with HttpClient rather than the library itself. Indeed, I've made a start on throwing together some HttpClient tests and will feedback.

You're absolutely right that I was using trying to build the PCL instead of CoreCLR. Doh!

**Comment by chris02031** [comment]
I've not been able to blow Azure up using HttpClient, but that may just be because I've not checked the responses from HttpClient, merely thrown out a large number of requests to see if HttpClient itself threw some error. Every port was tied up with an established connection, but nothing seemed to blow up... not sure if requests are then being queued for an available port (and that old ones are then released) or if new requests just faili at that stage... probably need to dig a bit deeper.

In the mean time I managed to get the library built. Woohoo for open source.

One thing that seems odd is this WrappedStorageException - it isn't intuitive that it inherits from COMException (or why it doesn't just throw the StorageException... ), but explains why my original catch on System.Exception wasn't working. For me this is actually the revelation that makes the whole library usable - I can actually handle the exception and requeue a disrupted request for example instead of blowing up. I've just added 2m rows flawlessly from my home machine, now for Azure...

**Comment by chris02031** [comment]
So, Azure... it works.

I've not really changed anything so I don't think it's anything I've done. The code still blew up Azure before I made the usual registry changes as per https://msdn.microsoft.com/en-us/library/aa560610%28v=bts.20%29.aspx, but after that it was fine.

Those basic registry changes were one of the earliest things I tried... maybe the problem all along has been that not being applied to my Azure vm properly?

**Comment by pemari-msft** [comment]
Great! That's encouraging. Yes, the WrappedStorageException/StorageException issue is actually an artifact that needs to be fixed -- it's on our backlog to fix that in an upcoming major version release. Apologies on that front. 

And now I see your update too. Well, that's interesting. I'm glad it's working now, at least. Thanks for doing the legwork to chase it down and make sure there wasn't a mistake in the library.

**Comment by chris02031** [comment]
Sounds like you guys are on top of it - I'll be interested to check out the next release!

Glad to be up and running too, and it's brilliant to be able to communication with you guys directly - makes said legwork a lot easier. Appreciate your time and thought - keep up the good work.
