### ISSUE TITLE
make setter IsEncrypted on EntityProperty public so can Encrypt the DynamicTableEntity 

### ISSUE THREAD

**Issue by liuhongbo** [Azure/azure-storage-net#199]
I didn't find an easy way to encrypt DynamicTableEntity.
By make the  setter IsEncrypted on EntityProperty public,  will enable us to choose which field(s) we can encrypt on the entity.

**Comment by mirobers** [comment]
To select which properties are encrypted in a DynamicTableEntity, set the [EncryptionResolver](https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/Table/TableRequestOptions.cs#L257) property on TableRequestOptions. This is a delegate that accepts the partition key, the row key, and the property name and returns a bool indicating whether the property should be encrypted.

**Comment by liuhongbo** [comment]
my thought is that might not be the best way to do it. 

1. TableRequestOptions  is passed into the Execute where that piece of code normally sits in the layer of the software that has no knowledge of the entity details; 

2. If I have 100 entities/tables, I have to write 100 EncryptionResolvers, because by just looking at pk, rk and property name, I might not even be able to tell which entity the property comes from;

3. deriving entity from DynamicTableEntity might not be used often, but sometime it is useful

**Comment by mirobers** [comment]
We can take it as a feature request to specify that info on the EntityProperty directly. This would require you to set this once per entity rather than once per logical encryption schema. (Typically more than one entity would encrypt the same sets of columns, so you could reuse a resolver in such cases.) If you have no such schemas then I agree it makes sense to have this info embedded in the entity itself (i.e. any column may or may not be encrypted -- independently of the encryption on that column in other entities).

DynamicTableEntity is currently sealed, so I am not sure how you are deriving from this class. In any case, the EncryptionResolver works for all entity types.

**Comment by liuhongbo** [comment]
Right,  my point on #3 is not correct.   I can not deriving from DynamicTableEntity right now.. 

Just want to be clear, When I say 100 entities, what I really mean is entity types. that will go to different tables in the azure table storage.  So, each entity type will have different set of columns.

Then if the code doing the table execute operation is shared by all the entity types/tables, the EncryptionResolver will do a switch on table name first, then switch on the column name. which works, but when I added a new table, or new column that needs to encrypt, I have to modify that EncryptionResolver add more switch cases.

Just think  having the IsEncrypted public accessible will end up better code. Plus,  have IsEncrypted public is about equivalent of the  EncryptPropertyAttribute.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
