### ISSUE TITLE
Request: Proxy Support

### ISSUE THREAD

**Issue by lynnette-lines** [Azure/azure-storage-net#218]
The Azure storage library for Java (Azure/azure-storage-java) has support for specifying a Proxy, which was added in version 3.1.  Would it be possible to add an equivalent feature to the .net library?

**Comment by pemari-msft** [comment]
Would you be willing to share more about your scenario? This already could be accomplished by using the Protocol layer of the library which returns an HttpWebRequest, could that perhaps be a workaround? 

We can take it as a feature request, but I'd like to understand more so I can make sure the request is adequately addressed. Thanks!

**Comment by pemari-msft** [comment]
Thanks for the feedback. As I mentioned, we added this to our feature request backlog. Please feel free to reopen to provide more information about your scenario.

**Comment by max-vogler** [comment]
Writing a `.NETCoreApp,Version=v1.1`, using `"WindowsAzure.Storage": "7.2.1"`, `dnxcore50`, and `portable-net45`, we stumbled upon this exact issue: There is no apparent way to configure the Azure .NET SDK for proxy usage with .NET Core.

- Supplying `<configuration><system.net><defaultProxy>` in `app.config` had no effect, most probably because .NET Core does not parse `app.config`. 
- Setting `WebRequest.DefaultWebProxy` allowed us to route our own `HttpWebRequest`s through the proxy, but not requests by the Azure SDK. 
- The only visible proxy setting that `CloudStorageAccount`, `CloudBlobClient`, and all other Storage SDKs provide is `DevelopmentStorageProxyUri` in the connection string. But that seems to only affect the development storage.

You can find a minimal-but-complete example in [this gist](https://gist.github.com/max-vogler/d117608e9400264f98d2bac3a036b96a). It basically boils down to:
```cs
WebRequest.DefaultWebProxy = new MyProxy();
HttpWebRequest.DefaultWebProxy = new MyProxy();

var account = CloudStorageAccount.Parse("DefaultEndpointsProtocol=https;AccountName=...;AccountKey=...");
var blobClient = account.CreateCloudBlobClient();
var container = blobClient.GetContainerReference("test");
var blob = container.GetBlockBlobReference("test");

Console.WriteLine(blob.DownloadTextAsync().Result);
```

**Comment by SeanFeldman** [comment]
That's a feature I'd like to see as well. With `WebRequest` being deprecated, it would be nice to have this supported.
@pemari-msft was this out of backlog and implemented? What's a tracking issue to subscribe to?
