### ISSUE TITLE
Request: Make TableOperation constructor public

### ISSUE THREAD

**Issue by arangas** [Azure/azure-storage-net#229]
The TableOperation class has lots of helper .Insert, .Replace, etc... methods which is great. However there are also times when it would be helpful to do: `new TableOperation(entity, operation);` as the [internal constructor provides](https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/Table/TableOperation.Common.cs#L41).

The main reason is for wrapping functionality around table operations, where the ability to pass the entity and operation itself around as variables would be really helpful. Otherwise it is necessary to resort to at least one lengthy `if` statement to convert an operation to its corresponding static method in TableOperation.

Would this be possible, or is there a particular reason why this is marked internal? (Happy to provide a PR.)

**Comment by pemari-msft** [comment]
Generally, the reason for internal constructors and these helper methods is to ensure validations in order to fail fast on the client side. Whenever internal constructors exist in the library it's because there's only certain cases where they should be used (because we make assumptions about the state of things at the time they are called). Therefore, the change would have to be larger than simply making it public in order to maintain this safety.
