### ISSUE TITLE
Rename the default namespace from 'Microsoft.WindowsAzure' to 'Microsoft.Azure'.

### ISSUE THREAD

**Issue by olegburov** [Azure/azure-storage-net#234]
It has been 2 years since Microsoft renamed Windows Azure to Microsoft Azure. However, the default namespace still comes as `Microsoft.WindowsAzure`. It would be nice if you renamed them to `Microsoft.Azure` one.

**Comment by pemari-msft** [comment]
Hi @olegburov,

Yes, it's true that it has been a bit since the rebranding. However, to change the namespace would be a massive breaking change -- one that would affect at least every Storage import statement in every file in our customers' codebase. This is a rather unpleasant change for no benefit. 
If in the future we have a similarly large breaking change that provides real functionality improvements to the library, we certainly will look to include this change as well. 
Thanks for the suggestion!
