### ISSUE TITLE
Feature Request: Linq TableQueries for PCL Profile 111

### ISSUE THREAD

**Issue by CrazyTuna** [Azure/azure-storage-net#265]
I am building an application that target the PCL Profile 111. 
I've installed the nuget package WindowsAzure.Storage v7.0.1-preview.

Using a previous version of the WindowsAzure.Storage library (for another project), I was able to query an Azure Table Storage using linq like that :

```
var cloudTable = GetCloudTable();
var query = cloudTable.CreateQuery<DynamicTableEntity>()
    .Where(e => e.PartitionKey == "PartitionKey");

```

Do you plan to add Linq capability for PCL Profile 111 ?

Cheers,

**Comment by pemari-msft** [comment]
For now, the PCL is still in preview. However, we will take this as a feature request and add it to our backlog. Thanks for the suggestion!

**Comment by erezvani1529** [comment]
Hi,

Since the release of CosmosDB Table sdk [package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/), 
support for Table service has transitioned to CosmosDB team.

CosmosDB has planned support for Netstandard targets > 1.3 which will include this feature request, 
Please email the team at : `askcosmosdbtableapi@microsoft.com` for support or more information. 

Thanks!
