### ISSUE TITLE
ETA on RTM of WindowsAzure.Storage for .NET Core RTM?

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-storage-net#298]
With .NET Core hitting RTM today, we're currently using the `7.0.2-preview` package, which seems compatible (based on minimal testing this morning), but I was wondering if there is an ETA for a final `WindowsAzure.Storage` RTM lib with compat with .NET Core RTM?

**Comment by niemyjski** [comment]
Also could use packages for service bus + queues

**Comment by pemari-msft** [comment]
Hi @GuardRex -- yes, we are working closely with the .NET Core team in order to have support for .NET Core RTM as soon as possible. However, there are still some blocking bugs that we've filed that they're working on fixing. In the interest of transparency, here's how the process has been working: we do try out their builds as they're being worked on, and report any bugs that we may find. When the packages get released to nuget, we do another round of tests, then the packaging and shipping work to support the new version. Then we attach that work to our next release train. We're targeting that release within a week or two (depending on our final tests/validations), but it will still be a preview release for us because we are not able to GA a package that has the blocking bugs we've reported. 

Please do let us know if you find any issues with it in your testing as well :) We'll let you know as we zero in on an exact release date.

**Comment by GuardRex** [comment]
I see. It's unfortunate that the blocking bugs exist. I can't wrap a contact and deliver a project to a client based on the preview lib (my contract stipulates 'no preview components' in the project), and I really would prefer not to go back to using the REST API for this. I guess I'll *very loosely* suppose that it could take a month for you to hit GA. I need to tell the client *something*.

**Comment by pemari-msft** [comment]
@niemyjski Azure Service Bus is a completely different service. They do have an SDK, located on nuget: https://www.nuget.org/packages/WindowsAzure.ServiceBus. Please feel free to reach out to them if you have any problems with it :)

**Comment by niemyjski** [comment]
@pemari-msft can you please link us to the issues that are currently blocking you.

**Comment by mirobers** [comment]
The current blocker is dotnet/corefx#9433
Our plan is GA by the end of July, once we ensure a GA quality release. The Core platform itself just went RTM recently, and there is work to make sure things are at a state we can call GA. (Update our infrastructure, platform testing, stress testing, etc.)
Meanwhile, we are updating our preview support for Core RTM. This will make it out within the preview flavor of the 7.1 release today. There is more to do before GA but we are almost there!

**Comment by niemyjski** [comment]
Just curious... Why would you define your own custom response header when there is a built in one for the http spec that would work...........

Get Outlook for iOS




On Thu, Jun 30, 2016 at 6:51 PM -0500, "Michael Roberson (Microsoft)" <notifications@github.com> wrote:












The current blocker is dotnet/corefx#9433

Our plan is GA by the end of July, once we ensure a GA quality release. The Core platform itself just went RTM recently, and there is work to make sure things are at a state we can call GA. (Update our infrastructure, platform testing, stress testing, etc.)

Meanwhile, we are updating our preview support for Core RTM. This will make it out within the preview flavor of the 7.1 release today. There is more to do before GA but we are almost there!

**Comment by mirobers** [comment]
I think you are referring to the x-ms-content-type header. This is used to hold the content type of a blob when that blob is not the payload of the HTTP message. In other words, HTTP says that Content-Type is the type of the HTTP message payload, but APIs such as PutBlockList send the content type of the blob along with an XML payload (the block list). Therefore x-ms-content-type is used to avoid implying that the type applies to the list itself.

We use Content-Type when it is appropriate according to HTTP (i.e. GET or HEAD a blob).

**Comment by Eneuman** [comment]
"Today" is a very long day ;)

**Comment by mirobers** [comment]
All right, I should have said "within 24 hours". :wink: It's up on NuGet now. Let us know if you encounter any issues.

**Comment by Eneuman** [comment]
Awesome work!

**Comment by niemyjski** [comment]
https://github.com/Azure/azure-storage-net/issues/311
