### ISSUE TITLE
support dotnet core

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-storage-net#319]
Please add support for .net core!

Here are the errors you get if you attempt to add this package to a dotnet core app

```
Errors in Project.xproj
    Package System.Spatial 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Spatial 5.6.4 supports:
      - net40 (.NETFramework,Version=v4.0)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      - sl4 (Silverlight,Version=v4.0)
    Package Microsoft.Data.Services.Client 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Data.Services.Client 5.6.4 supports:
      - net40 (.NETFramework,Version=v4.0)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      - sl4 (Silverlight,Version=v4.0)
    Package Microsoft.Data.OData 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Data.OData 5.6.4 supports:
      - net40 (.NETFramework,Version=v4.0)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      - sl4 (Silverlight,Version=v4.0)
    Package Microsoft.Data.Edm 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Data.Edm 5.6.4 supports:
      - net40 (.NETFramework,Version=v4.0)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      - sl4 (Silverlight,Version=v4.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

Maybe this project needs to be split into separate packages for blob/queue/table functionality to aid the process.  It seems unfortunate that I only want to work with queues and blobs and I am failing on dependencies like System.Spatial, Microsoft.Data.Edm, etc...

**Comment by GuardRex** [comment]
@gregjhogan They do ... it's just some of the supporting packages that don't explicitly support the `netcoreapp1.0` TFM. Those packages do work. You need to add an `imports` statement to your TFM ...
```c#
"frameworks": {
    "netcoreapp1.0": {
        "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
},
```
WRT splitting the lib, they've already said 'no' to that request: https://github.com/Azure/azure-storage-net/issues/97#issuecomment-191012939

**Comment by gregjhogan** [comment]
@GuardRex thanks for the info!  Does adding a dependency on `portable-net45+win8` cause my application to only run on windows?  If yes, this is not a viable solution for me.

@mirobers I wish #97 wasn't closed for comments.  It states the following reason for not splitting:

> * There is no major problem with the current design and there are few benefits to changing it. We have ourselves seen no problems with maintenance or portability due to dependencies.

Isn't this a portability issue due to dependencies?

**Comment by GuardRex** [comment]
@gregjhogan No ... It's fine to add it. The `imports` only specify TFM's that should be accepted regardless of their compatibility with the framework you specify. You're not actually adding `portable-net45+win8` as a TFM to your app ... you're just saying that packages that target the `portable-net45+win8` TFM *will work* with the `netcoreapp1.0` TFM (even if they don't :smile: ).

**Comment by gregjhogan** [comment]
@GuardRex can you point me somewhere that explains this?  It is obviously not intuitive that I can use a target platform moniker with windows in the name and run it on linux.  I am trying to understand the how/why this works.  Thanks!

**Comment by GuardRex** [comment]
Unfortunately, the docs for .NET Core are still evolving right now https://docs.microsoft.com/en-us/dotnet/articles/core/index (and they aren't searchable :frowning: ). However, they just hired @spboyer to help spruce them up a bit.

You can at least get a decent definition of the `imports` section at http://docs.nuget.org/consume/projectjson-format ... but that's a rather old doc, so don't trust the entire doc too much. The `Imports` section of the doc is fine to answer your question on an official source.

> not intuitive that I can use a target platform moniker with windows in the name and run it on linux

You are correct ... It's not intuitive, but that's because these underlying packages are still using the old PCL target system and don't know anything about the .NET Standard.

`netcoreapp1.0` is a Core CLR TFM and cross-platform. These underlying packages *are compatible* with Core CLR and will work cross-platform ... they just don't say that they meet .NET Standard for Core. When these packages get upgraded for .NET Standard, they will get a .NET Standard TFM (e.g., `netstandard1.3` or whatever), then the imports for these old TFM's will not be needed.

In the meantime, you have to "import" them with a TFM that they say they will support in order to **force** the tooling to accept them. All you're saying here for these packages is "Use these! I'm telling you they will work with the `netcoreapp1.0` TFM." [Even if they won't work and :boom: at runtime.] In this case for Azure Storage and these underlying packages, we do know that they work, and we know that they work cross-plat for a Core CLR app, including Linux.

There has been discussion on when they will be updated. It looks like it will take a bit longer. See. https://github.com/OData/odata.net/issues/568 ... with some luck, maybe in August.

**Comment by gregjhogan** [comment]
@GuardRex does what you suggest currently require mono on Linux? Thanks!

**Comment by GuardRex** [comment]
I'm mostly a Windows cat :cat2:. There are a lot of Linux experts using .NET Core over at Slack. Visit with them in the #general channel, and I'm sure they can help. http://tattoocoder.com/aspnet-slack-sign-up/

**Comment by pemari-msft** [comment]
Glad you got it figured out -- we documented this in our readme as well. Hopefully OData can fix this soon.

**Comment by mac2000** [comment]
If you are on new csproj you will need to add `<PackageTargetFallback Condition=" '$(TargetFramework)' == 'netcoreapp1.1' ">$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback>` right after `<TargetFramework>netcoreapp1.1</TargetFramework>` that is an equivalent to imports in json

**Comment by erezvani1529** [comment]
Some good news regarding netstandard friendly OData package:

As a result of our collaboration with CoreFx team, we have updated our library ([v8.1](https://www.nuget.org/packages/WindowsAzure.Storage/8.1.0)) to use the latest Netstandard friendly ODataLib packages to eliminate the need to import or add additional TFs. 

Thanks for your patience and help while we are working on the [remaining issues ](https://github.com/Azure/azure-storage-net/issues/372)with ODataLib.

-Elham

**Comment by StenPetrov** [comment]
This still doesn't work

**Comment by erezvani1529** [comment]
Hi @StenPetrov,

Would you please share more details on the issue you are observing?

Thanks!
