### ISSUE TITLE
I must have a misunderstanding on how to use Take() with a segmented query

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-storage-net#323]
For my `int` var `takeCount`, this isn't working. It's returning all of the entities in the table (`7.1.3-preview` and `netstandard1.0` app). I read that in ancient times there was a bug but that it was fixed. http://stackoverflow.com/a/15804671
```c#
TableQuery<T> query = new TableQuery<T>().Take(takeCount);
TableContinuationToken token = null;
List<T> resultSet = new List<T>();
do
{
    var seg = await table.ExecuteQuerySegmentedAsync<T>(query, token);
    token = seg.ContinuationToken;
    resultSet.AddRange(seg.Results);
}
while(token != null);
```
should the `while` be setup like this http://stackoverflow.com/a/27758787 ...
```c#
while(token != null && (query.TakeCount == null || resultSet.Count < takeCount));
```
If that's correct (or something close to that is correct), then why can't the storage service keep track of the number of entities returned, stop itself on the last entity needed, and null the token on its own?

While we're at it, `Take()` vs `TakeCount()`: I expected the difference to be that the former will limit the return of entities and the latter will set the segment count size for each segment of returned results within the `do-while`.

Take() from MSDN https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.storage.table.tablequery.take.aspx ...

> Defines the upper bound for the number of entities the query returns.

... and no example.

TakeCount from MSDN https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.storage.table.tablequery.takecount.aspx...

> Gets or sets the number of entities the table query will return.

... and no example.

... **not helpful**. Google Fu and Bing Fu for "azure table storage take vs takecount" gets ya nowhere fast. The docs at https://azure.microsoft.com/en-us/documentation/services/storage/ don't discuss. Do you have a doc reference that explains the difference?

**Comment by mirobers** [comment]
The underlying issue is that the storage service doesn't treat $top as the result set size. It treats it as a max page size. Therefore when you are using the segmented methods, simply following the continuations returned by the service will get you more total results than the TakeCount of the individual calls.

The storage client used to have the same bug in its IEnumerable implementation of continuation handling, but this has been fixed for quite some time. The fix is to keep track of how many items have been iterated in total and stop iteration after reaching TakeCount.

Take() is simply a fluent method for setting the property TakeCount. So they are the same, which explains why they have near-identical documentation. Sorry for the confusion.

**Comment by GuardRex** [comment]
Ah! Thanks ... that clears it up. :+1: :smile:
