### ISSUE TITLE
Incorrect/confusing error message on bad blob refrence

### ISSUE THREAD

**Issue by lasrol** [Azure/azure-storage-net#329]
We are using the WindowsAzure.Storage 7.1.3-preview in netstandard1.6 project and had some some issues when trying to upload a blob. In our case we had a bug that formatted the id for the blockblobreference badly. The id had this value **xxxxxxx.["FileNameExtension",".jpg"]**

The error message we got back was 

> StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

I am not sure if this is a bug really, but i think in the case the BlockBlobReference is not formatted correctly, there should be a better error message?

The exception happend on UploadFromStreamAsync method

```
CloudBlockBlob blockBob = container.GetBlockBlobReference(id);  
await blockBob.UploadFromStreamAsync(data);
```

**Comment by GuardRex** [comment]
I'll hazard a quick guess on that: The blob filename (or "CanonicalizedResource" in REST parlance) becomes part of the shared key signature (i.e., part of the authorization header). See: https://msdn.microsoft.com/en-us/library/azure/dd179428.aspx

Because it was being formed and provided to the service in an invalid format, the exception saying the authorization header is bad came back.

I do agree though with the thrust of your comment: If the storage lib could Regex the filename or something to flag a bad format or illegal characters, that would be helpful in a case like this ....... throw an invalid argument or something along those lines.

**Comment by pemari-msft** [comment]
@lasrol Thanks for reporting this, we'll take a look as to what specifically is causing the problem here, because nothing that you have there should be an invalid blob name. ( /cc @jofriedm-msft )

@GuardRex You may be interested in using the [NameValidator ](https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/NameValidator.cs) class ;)

**Comment by GuardRex** [comment]
^^ Well ... that was just a guess. :wink:

Ah! https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.storage.namevalidator.aspx

Very nice! :+1:

**Comment by jofriedm-msft** [comment]
Hi @lasrol and @GuardRex , we took a look and it appears that CoreFX is not giving us the exact percent encoding URI that is sent on the wire. I have added a follow up comment on an open issue with them in #6946

**Comment by GuardRex** [comment]
@jofriedm-msft mmmmm, yeah ... I had a similar issue earlier with their bits ... I had my "fun" with teasing out a problem where the auth header was malformed due to the charset being added to the `Content-Type` automatically and without my knowledge by `StringContent()` ... the mismatch between what I was sending and what was in the auth header gave me a big 'ole :boom:. https://github.com/dotnet/corefx/issues/7864

**Comment by jofriedm-msft** [comment]
@lasrol  and @GuardRex 

This issue should be fixed in the Corefx library by this change in an upcoming release
https://github.com/dotnet/corefx/pull/11159

**Comment by pemari-msft** [comment]
I'm going to close this issue as it has been resolved by the CoreFx team.
