### ISSUE TITLE
Reference to Microsoft.Data libraries

### ISSUE THREAD

**Issue by KevinCocquyt39** [Azure/azure-storage-net#348]
Within this project, there are still some references to an old version of the Data libraries.
Eg. package id="Microsoft.Data.Edm" version="5.6.4" targetFramework="net40-Client"

Downloading the WindowsAzure.Storage library gets the latest version of the Data libraries (v5.7.0) and places 'redirect assembly rules' in the web.config, making sure all references to the Data libraries will point to version 5.7.0. Problem now is, whilst targeting 5.6.4, the redirects will point it to 5.7.0 but as it does not exist (NET 4.0 limitation?), the Data libraries could not be found, resulting in a error on our website.

It is possible to update the target framework, or making sure the rules say >= 5.6.4 & < 5.7.0?

**Comment by erezvani1529** [comment]
Hi @KevinCocquyt39, 

You should be able to modify the binding redirect rules to use the 5.6.4 version to avoid the problem you have mentioned. 

Meanwhile, we are planning to upgrade our desktop version to target net452 in our upcoming release (v8.0) which will include the updated reference to the latest version of the OData library.

Thanks!

**Comment by KevinCocquyt39** [comment]
Hi,

Thanks for the quick answer. We will change the redirect then. That was already a idea of mine but I wanted to make sure I wasn't missing something. Cross references can be hard to detect sometimes :)

Kind regards,
Kevin

**Comment by rambo-msft** [comment]
Great! Feel free to open this back up if you run into any more issues.
Thanks.

**Comment by DavidDeSloovere** [comment]
I believe the issues we ( @KevinCocquyt39 is my collegue) had was a mix of 
- the references to 5.6.4 from the nuget packages
- the build server having a local installation of Microsoft WCF Data Services, with 5.6 and 5.6.4
- and indirect references in a web project

ODdata package 5.7.0 is installed, bindingredirects are good. However...
The result was that 2 of the 3 web projects were ok, but the 3rd one sometimes had the 5.6.4 dlls in the output. 
I renamed the location Microsoft WCF Data Services folder into something else and have been able to get a few consecutive and succesful builds out of it.

So the real cause might be build server or build related; instead of references in nuget packages or binding redirects.

I don't know how these dlls wrongfully end up in the project, but I've seen it happen before with other projects in the same solution (console apps). If anyone has a link for me to find out more about this, that would be great.
