### ISSUE TITLE
StorageException in DownloadToByteArrayAsync

### ISSUE THREAD

**Issue by VictorNicollet** [Azure/azure-storage-net#366]
I use `DownloadToByteArrayAsync` to read from the end of an Append Blob, using this call: 

```
var position = ...; // The value of 'blob.Properties.Length' at some point in the past

var context = new OperationContext();
context.SendingRequest += (sender, e) => { e.Request.Headers["if-match"] = "*"; };

var length = await blob.DownloadRangeToByteArrayAsync(
  _buffer,
  0,
  position, 
  _buffer.Length,
  new AccessCondition(),
  new BlobRequestOptions(),
  context,
  cancel);
``` 

I expect this call to read any bytes past `position` into `_buffer`, and to return the number of bytes read. However, if another process is currently appending to the blob, this call sometimes throws an exception: 

```
Microsoft.WindowsAzure.Storage.StorageException: Incorrect number of bytes received. Expected '3443580', received '3443752'
at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End()
at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.EndDownloadRangeToByteArray(System.IAsyncResult)
at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions+<>c__DisplayClass1`1.<CreateCallback>b__0(System.IAsyncResult)
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at AzureEventStore.Core.Drivers.AzureStorageDriver+<ReadAsync>d__15.MoveNext()
```

**Comment by mirobers** [comment]
Is position+_buffer.Length greater than the length of the blob? If so, you are probably hitting a case where the download fails and is internally resumed, but the two operations disagree in the total number of bytes returned due the concurrent append. This is only an issue because you are explicitly bypassing the ETag check, which would normally detect and fail such requests in the presence of concurrent modification.

We can accommodate this scenario so that the data returned is consistent with the length of the initial request to the service. As a workaround, consider adjusting the requested length so position+length is not greater than the length of the blob.

**Comment by VictorNicollet** [comment]
It was my understanding (but the documentation is vague on this point) that the `DownloadRangeAsByteArrayAsync` functions returned the number of bytes read because that number could be smaller than the requested length (in cases where `offset + length` exceeds the length of the blob). If the expected behavior is that the call should fail if the range goes past the end of the blob (and therefore, the return value is always the `length` parameter), then I should probably look for another solution. 

My application reads from an Append Blob, polling for new data every few seconds (this new data is appended by other processes). I perform this call as part of the polling loop, each time with a `position` equal to the length of the blob and a `_buffer.Length` of 4MB. The observed behavior is that: 

 - if no concurrent write happened since the last poll, it returns a length of 0 and reads no bytes.
 - if a concurrent write happened, it returns a length no larger than 4MB (but often smaller, if only a little data was written). My code then adds this length to `position` and performs the call again.
 - in rare cases, if a concurrent write has happened, the above `StorageException` is thrown, but most concurrent writes do _not_ cause the exception.

So, it certainly looks like `DownloadRangeAsByteArrayAsync` behaves as I expect it to, outside of those rare exceptions being thrown, but I could be relying on unintentional (or unspecified) behavior.

I am unable to provide a value of `position + _buffer.Length` that is smaller than the length of the blob, because I do not have access to the length of the blob. I could query for the blob metadata, but this would require two requests instead of only one in a rather latency-sensitive loop, for what I believe is a fairly simple "get new data" operation, so I would rather craft the HTTP GET request with an `x-ms-range` manually if doing so is not possible through the C# API.

Could I perhaps assume that if I do not provide the `length` parameter to `DownloadRangeAsByteArrayAsync`, the function will not attempt to read more data than necessary to fill the provided buffer ?

**Comment by mirobers** [comment]
The only problem is when there is a concurrent modification. Otherwise it behaves as you say. The client fails in the presence of concurrent modification due to the possibility of downloading corrupted data. So the client ensures there is no modification and makes the assumption that the size of the data downloaded is constant and no extra data shows up at the end of the blob. You are using SendingRequest to bypass the concurrent modification check and therefore the assumption is invalid in certain cases.

Again, we'll provide a fix that makes this work the way you expect. If the workaround of limiting the length of the range get doesn't work in your scenario, you could also simply catch the exception and retry the operation. Once the fix is out, you should not see this issue anymore.

**Comment by VictorNicollet** [comment]
Thank you. Again, I wouldn't really expect this to work on an arbitrary Block Blob (because the contents _can_ change at random), but I do expect an Append blob to be append-only.

**Comment by seanmcc-msft** [comment]
Please reactivate if you are still experiencing this issue.
