### ISSUE TITLE
Table Creation failing with 400?

### ISSUE THREAD

**Issue by chrispatrick** [Azure/azure-storage-net#368]
So far I have been unable to fully test this, but I am trying to create a new table in a new Storage Account but I get a 400 every time. I have checked and double checked the connection string and the table name and they all look to be correct.

I did start to investigate further with Fiddler and noticed that the POST request ends in `/Tables()` which is different from what is in the API documentation at https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/create-table

I'm not sure if this is the issue but if I reissue the same request from fiddler with out the parentheses, I get a 403 instead of the 400...

**Comment by pemari-msft** [comment]
Hi @chrispatrick. It's not clear what part of your request is incorrect just from this, but if you could send an `x-ms-request-id`, timeframe, and account name to ascl [at] Microsoft [dot] com, I will take a look at our server side logs and confirm for you. Thanks!

**Comment by asorrin-msft** [comment]
Discussed offline, but as FYI in case anyone else has this issue - 
It turns out we have a bug in the client-side encryption logic.  Normally, inserting an entity into a table will automatically (invisibly to the caller) add the encryption metadata to the request.  There is special logic in the CreateTable() API to not do this (because the create table call can't be encrypted.)  The bug is that this logic is only hit if the encryption policy is specified in the RequestOptions object that's being directly passed into the CreateTable operation.  If the EncryptionPolicy is instead specified in the TableClient.DefaultRequestOptions, the client is incorrectly adding the encryption data to the request, causing it to fail on the service.

This will be fixed in the 8.0 release.  Until then, the workaround is to not have the DefaultRequestOptions in the table client have an encryption policy (or the requireEncryption flag) set during the CreateTable call.  This can be done by modifying the request options object before and after the create call, by using different CloudTableClient objects for the Create call and other operations, passing the requestOptions directly into the Create() and Execute() table operations, etc.

Thanks for reporting this!  We'll close this issue when 8.0 ships.

**Comment by erezvani1529** [comment]
Hi @chrispatrick,

Thanks again for reporting this issue. [8.0](https://www.nuget.org/packages/WindowsAzure.Storage/8.0.0) is published with a fix.

Thanks!
