### ISSUE TITLE
Wrong content-type when downloading file from Storage Emulator

### ISSUE THREAD

**Issue by Eneuman** [Azure/azure-storage-net#373]
I'm using Storage Emulator 4.5 and Google Chrome Version 55.0.2883.87 m (64-bit)
I uploaded a file and set the content type to "image/png". 
I double check the content type of the file using VS2015 Cloud Explorer.

When running the following code, it always returns Content Type "application/octet-stream".

```
var xhr = new XMLHttpRequest();
xhr.open('GET', 'http://127.0.0.1:10000/devstoreaccount1/system/Logga.png', true);
xhr.responseType = 'blob';
xhr.onload = function (e) {
    alert(this.response.type);
};
xhr.send();

```

Shouldn't it return my set content type of "image/png"?

**Comment by mirobers** [comment]
Hi @Eneuman, I think when you call this.response.type your are not reading the response from the emulator. I'm far from an expert on XMLHttpRequest, but I think you might need to call xhr.getResponseHeader instead.

Otherwise, you can try tracing the request to ensure that the correct content type is being returned from the emulator.

**Comment by pemari-msft** [comment]
Closing for nonresponse. Please let us know if you see further issues!
