### ISSUE TITLE
No CancellationToken on async methods on ICloudBlob interface

### ISSUE THREAD

**Issue by Jericho** [Azure/azure-storage-net#382]
Is there a reason why async methods on the ICloudBlob interface do not have a cancelletion token parameter? There are about 20 or so async methods on the interface and none of them accept a CancellationToken parameter. Here's one example:
```
Task<bool> ExistsAsync(BlobRequestOptions options, OperationContext operationContext);
```

However, the `CloudBlob` concrete class implements an overload with the cancellation token parameter in addition to the overload without the parameter:
```
public virtual Task<bool> ExistsAsync(BlobRequestOptions options, OperationContext operationContext)
public virtual Task<bool> ExistsAsync(BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
```

___Note:___
 I'm using version 8.0.0 of the nuget package

**Comment by Jericho** [comment]
Wouldn't it make more sense to have the following in the interface:
```
Task<bool> ExistsAsync(BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken);
```

and one single method in the concrete class (notice the cancellation token is optional):
```
 public virtual Task<bool> ExistsAsync(BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken = default(cancellationToken))
```

**Comment by Jericho** [comment]
To add to the confusion, I found two more versions of the `ICloudBlob` interface in the source code:

There's a [Façade](https://github.com/Azure/azure-storage-net/blob/afc5c6d99a805fb4165631ab5cfd139238b00e71/Lib/AspNet/Microsoft.WindowsAzure.Storage.Facade/FacadeLib/Microsoft.WindowsAzure.Storage.Blob.ICloudBlob.cs#L103) version and there is a [WindowsRuntime](https://github.com/Azure/azure-storage-net/blob/68c3ee55a3a6f62a0159cea58005d3fe027312a8/Lib/WindowsRuntime/Blob/ICloudBlob.cs#L257) version both of which are missing the CancellationToken parameter.

My project is targeting `.netstandard1.6` which makes me think that it's referencing the "Façade" version which would explain why I am not seeing the cancellation token.

So I guess I should rephrase my original question: Is there a reason why the methods in the "façade" for `.netstandard` are missing the CancellationToken parameter?

**Comment by erezvani1529** [comment]
Hi @Jericho,

**First a quick clarification:** Currently, we maintain two code-bases to support multiple targets including Desktop and Runtime/Netcore. Our Desktop code-base is a super-set of the Runtime/Netcore code-base and it is on our [roadmap](https://github.com/Azure/azure-storage-net/issues/338) to move towards parity between these two with general availability of Netstandard. This addresses the fact that you see multiple versions of ICloudBlob (and since you are targeting netstanard you are using our [Runtime/NetCore codebase](https://github.com/Azure/azure-storage-net/blob/68c3ee55a3a6f62a0159cea58005d3fe027312a8/Lib/WindowsRuntime/Blob/ICloudBlob.cs#L257)).

One more point: Your project is not in fact referencing the Façade. We have multiple netstandard targets in our nuget and given that your project is targeting netstandard1.6, by referencing our nuget package, your project should automatically pick up the dll targeting netstandard1.3 as a reference.

Coming back to your original suggestion: 

> Is there a reason why async methods on the ICloudBlob interface do not have a cancelletion token parameter

 Since we are planing to move forward from ICloudBlob and replace it with CloudBlob in future releases, would you please clarify your scenario where using ICloudBlob can not be replaced with CloudBlob (which includes the certain APIs you have mentioned)?

Thanks!

**Comment by Jericho** [comment]
I was not aware that you were planning to eliminate the interface in favor of the concrete class in future versions (I read the roadmap article and didn't notice anything about that, maybe I missed something?).

I was writing extension methods and I figured I would target the interface since all blobs (block, append, page) implement it and therefore my extension methods would apply to all of them. If I have to switch to `CloubBlob` so be it, I have no objection. I was just using the interface because I thought it was the "lowest common denominator".

**Comment by mirobers** [comment]
Yes, the CloudBlob class is the lowest common denominator you're looking for. I'd recommend using it for sure. We went with a concrete base class because it's often useful to get a reference to a blob of unknown type. But as a consequence the interface is not very useful and we're starting to look at it as a candidate for deprecation.

**Comment by Jericho** [comment]
One of the reason why I chose ICloudBlob initially is that it's very easy to mock an interface. Unfortunately, it's no so easy to mock the CloubBlob interface

Specifically, the following unit testing code:
```
var mockBlob = new Mock<CloudBlockBlob>(MockBehavior.Strict);
```

Causes the following exception:
```
Can not instantiate proxy of class: Microsoft.WindowsAzure.Storage.Blob.CloudBlob.
Could not find a parameterless constructor.
```
