### ISSUE TITLE
Add enum support to TableEntity

### ISSUE THREAD

**Issue by DixonDs** [Azure/azure-storage-net#383]
Currently `TableEntity` skips enum properties from read/write operations. I think it should be pretty straightforward to add support to enums given that int/long values are supported.

**Comment by doguva-msft** [comment]
just fyi, TableEntity.Flatten and ConvertBack public static methods support enum properties.

**Comment by DL-LiveTiles** [comment]
This is such a basic requirement and enums natively support casting to int and vice versa.

**Comment by pemari-msft** [comment]
We mirror the property types supported by the service, which is why it isn't supported natively. We support it using the flatten methods. Thanks!

**Comment by DL-LiveTiles** [comment]
This is so stupid, there is no warning or anything so if you forget to cast to int it just does not work.

**Comment by doguva-msft** [comment]
If you use the mentioned api s in this thread - TableEntity.Flatten and ConvertBack, there is no need for any cast. These api s do the conversion transparently. Apart from IEnumerable type properties, these api s allow pretty much all types to be written into table storage,that also includes enum s. It may be worth for you to try those. In addition, also checkout the TableEntityAdapter class in the SDK, which is a class that abstracts some of this for the clients and under the hood calls TableEntity.Flatten and ConvertBack methods.

**Comment by DL-LiveTiles** [comment]
@doguva-msft I'm not sure what you mean or why any additional SDK calls would be required. For all practical purposes an enum is a simple type that can be serialized and deserializer without any developer intervention required. Why is the enum in the below example not supported? The custom class inherits from TableEntity...
`public enum CustomEnum
    {
        Value1,
        Value2,
        Value3
    }

    public class CustomEntity : TableEntity
    {
        public string Id { get; set; }
        public CustomEnum Status { get; set; }
        public string Message { get; set; }
    }`

**Comment by doguva-msft** [comment]
Before responding, I just want to remind here that I am not from the product team but i worked with them in some features and this is probably my last response to this thread. 

Azure Table Storage service supports subset of OData Data Types (http://www.odata.org/). Enum is not a supported type by the service, in fact I don't think even it is a supported primitive data type by OData specification per se.

So that brings in the need for a conversion back and forth between Enum and the supported OData data types or any other non supported OData primitive type, irrespective of that conversion being easy or hard. The relevant question is where should that conversion logic reside. In developer's code, in the SDK or in the service itself.

The service does not go into the business of decision making and conversions and it has a clear Rest api and OData as its supported data types. (albeit a subset of OData protocol).

So it leaves 2 options where the conversion should go, either in your own code as a developer or in the SDK. We introduced these helper conversion methods as a convenience to the developer community to leverage so not only Enums but pretty much all data types bar IEnumerable s could be written and read from azure table storage.

Having said that, just looking at this from a developer experience perspective, I appreciate that it could be a much smoother experience for you, if these conversion api s (TableEntity.Flatten, ConvertBack) were embedded inside the SDK and they were called transparently under the hood. In which case you inheriting from TableEntity class would be enough and you would not have to explicitly call Flatten/ConvertBack api s..

That is something you could put as a new request as opposed to an issue.

Hope this helps,
Dogu

**Comment by DL-LiveTiles** [comment]
@doguva-msft do not really care where this logic live, that's for the team to decide, but leaving to each developer to implement seems unnecessary and against good coding practice.

Looking at the description it seems like it was raised as a feature request not a bug. Personally I prefer using GitHub over Uservoice or other channels even if all items are called issues. That's another challenge developers face, just figuring out how to connect to the team is a nightmare. Ideas on Uservoice, issues on GitHub and questions on Stack-overflow...how does the team let alone the users communicate and manage items effectively! Appoligies for the rant. Good luck on youre future endeavors.

**Comment by doguva-msft** [comment]
@DL-LiveTiles you do not really need to implement your own solution unless you wanted to, but you would still need to call the helper api s (TableEntity.Flatten / ConvertBack) provided by the SDK for the conversion logic back and forth. Like I said it would be smoother experience for developers, if all of this would be transparent. I recommend you to try the new api s and then just open up a request to embed them into the SDK transparently. Have a good day..

**Comment by tomasaschan** [comment]
I just arrived here looking for a solution to the same problem (storing and retrieving entities with `enum` properties as smoothly as possible). Notably lacking both from the answers in this thread and from [the docs on the `Flatten()` method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.table.tableentity.flatten?view=azure-dotnet), is info on where to get the `OperationContext` instance.

Given this example type (same as posted above in this thread):
```
public enum CustomEnum { Value1, Value2, Value3 }

public class CustomEntity : TableEntity {
    public string Id { get; set; }
    public CustomEnum Status { get; set; }
    public string Message { get; set; }
}
```
could someone post an example on how to use the `TableEntity.Flatten()` API?

**Comment by doguva-msft** [comment]
Below is a sample pseudo code. For the OperationContext You can pass either a new OperationContext() or else you should be able to pass null. OperationContext is mostly for logging purposes and not mandatory for the api s to work.  Another note is that CustomEntity class does not need to inherit from TableEntity class. TableEntity.Flatten api does not require that but you could still inherit from TableEntity class if you wanted to.


//Flatten object of type CustomEntity and convert it to a EntityProperty Dictionary
 Dictionary<string, EntityProperty> flattenedProperties = TableEntity.Flatten(customeEntityInstance, null);

// Create a DynamicTableEntity and set its PK and RK
DynamicTableEntity dynamicTableEntity = new DynamicTableEntity(partitionKey, rowKey);
dynamicTableEntity.Properties = flattenedProperties;

// Write the DynamicTableEntity to Azure Table Storage using client SDK

//Read the entity back from AzureTableStorage as DynamicTableEntity using the same PK and RK
DynamicTableEntity entity = [Read from Azure using the PK and RK];

//Convert the DynamicTableEntity back to original customEntity object written to the Table Storage.
 CustomEntity customEntity = TableEntity.ConvertBack<CustomEntity>(entity.Properties, null);

**Comment by dvky16** [comment]
This does not work for me. ConvertBack fails, claiming that no parameterless constructor exists for this object although I defined such a constructor in my CustomEntity class. Any suggestions?

**Comment by doguva-msft** [comment]
@dvky16 which .net framework are you using? Also is it possible to post the code causing the issue

**Comment by dvky16** [comment]
Don't know which .net framework I'm using. Thanks for the reply, but eventually I'm turning to solutions that don't require storing complex objects on an Azure table... although it may be the most strait-forward way to do what I'm after.

**Comment by johnny-smartly** [comment]
Not sure what the SDK devs problem here is, as it's dead simple to implement handling of enums; they are nothing more than integers, and casting is trivial. However, here is a very simple workaround in order to support enums in table stores:
---
// Ignored by TableStore SDK, as the type is enum
public MyCustomEnumType State {
    get => (MyCustomEnumType) _storeStateValue;
    set => _storeStateValue = (int)value;
} 

// Handled by the TableStore SDK, as it's an integer. However, this is the same as above.
public int _storeStateValue { get; set; }

**Comment by doguva-msft** [comment]
@johnny-smartly  see above thread, enums are already supported by the SDK via Flatten and ConvertBack api s.

**Comment by Obi-Dann** [comment]
Hi there, just landed here because I experienced the same problem, I agree with everyone above that it's not clear that one has to use `Flatten` and `ConvertBack`. What we had is just a class derived from `TableEntity` that we though was working with Enums, until we accidentally discovered that it does not. 

You can argue that we should have used Flatten and ConvertBack API, but the problem is that it's not clear we should have used them. There was no warning, error or any other indication that there's a problem.

It's kinda funny that people still get confused about this 5 years after it's been reported and nothing has been done to fix or communicate the issue better.


> //Flatten object of type CustomEntity and convert it to a EntityProperty Dictionary
> Dictionary<string, EntityProperty> flattenedProperties = TableEntity.Flatten(customeEntityInstance, null);
> 
> // Create a DynamicTableEntity and set its PK and RK
> DynamicTableEntity dynamicTableEntity = new DynamicTableEntity(partitionKey, rowKey);
> dynamicTableEntity.Properties = flattenedProperties;
> 
> // Write the DynamicTableEntity to Azure Table Storage using client SDK
> 
> //Read the entity back from AzureTableStorage as DynamicTableEntity using the same PK and RK
> DynamicTableEntity entity = [Read from Azure using the PK and RK];
> 
> //Convert the DynamicTableEntity back to original customEntity object written to the Table Storage.
> CustomEntity customEntity = TableEntity.ConvertBack(entity.Properties, null);

this seems like a lot of code to write, why not just support enums by default and remove all the friction? Or perhaps at least add a warning or some other indication that it's not supported by default?
