### ISSUE TITLE
ListBlobs method returns duplicate CloudBlobDirectory

### ISSUE THREAD

**Issue by digibusiness** [Azure/azure-storage-net#396]
Hi,
starting from this week, whenever I've been calling `ListBlobs` method of `CloudBlobContainer` class I've been obtaining a list with some duplicated `CloudBlobDirectory`.

With the help of Fiddler I found that this problem is related to the REST API "pagination" (behind the scenes multiple requests are performed with "marker" parameter): each duplicate directory/prefix is returned as the last element of a request and as the first of the next one, as you can see in the attached images below (in the first image there is only one BlobPrefix in the response, I think because in that prefix there are a lot of blobs).

![blob_issue_1](https://cloud.githubusercontent.com/assets/4192699/22070593/e1274cd4-dd9c-11e6-9671-91a3a784564d.png)

![blob_issue_2](https://cloud.githubusercontent.com/assets/4192699/22070598/e71c5be8-dd9c-11e6-97e1-c408e857e0a9.png)

I don't know if this is the correct behavior of the [REST API](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/list-blobs), but if so then the SDK should handle this scenario without returning duplicate directories.
As I stated before, last week this problem was not present.

Thank you

**Comment by mirobers** [comment]
This is a known issue on the storage service. The fix should be deployed by the end of February. This is a service-side fix that will require no client changes. For now, you can detect and remove the duplicates from your results. As you observed, the duplicate entries are always the last of one request and the first of the next.

Although this is not a recent regression, hitting this issue depends on how your data is load balanced in the backend and so the issue may come and go until the fix is deployed.

**Comment by digibusiness** [comment]
Thanks @mirobers for your reply.
I fix my code in this way:
`container.ListBlobs().GroupBy(b => b.Uri).Select(g => g.First())`
It's not very nice, but hopefully temporary...
