### ISSUE TITLE
Lost nuget support for VS2013

### ISSUE THREAD

**Issue by nitro52** [Azure/azure-storage-net#414]
I noticed that there was an update to azure storage but when you attempt to upgrade you get

Attempting to resolve dependency 'System.Linq.Queryable (≥ 4.0.0)'.
The 'System.Linq.Queryable 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.12.0.817'.

I've had this issue before where a .net core library is used but requires nuget 3.0. The problem though is that you can't upgrade nuget in vs2013 to 3.0. Does this mean vs2013 will no longer be supported?

**Comment by GuardRex** [comment]
I think it went end of life with the end of support updates on 10/11/2016.

https://support.microsoft.com/en-us/lifecycle/search?alpha=Microsoft%20Visual%20Studio%202013

**Comment by erezvani1529** [comment]
Hi @nitro52,

Thanks for reporting your issue. As @GuardRex has correctly mentioned, we are indeed planning to move away from supporting VS2013 in close future. However, the issue you have mentioned, is a real nuget issue which we are actively following up at the moment. You are already referencing our library which includes a netstandard target. However, the issue here is with the ODataLib package nuspec with nuget client, where Netstandard target is being given priority over the NetFx one (we have suggested a temporary fix to ODataLib team to but there is no exact timeline as to when the fix will be published).

As a workaround, please try using the nuget client 3.0+ from a command line to install the updated package 8.1.0 (Also please not that there are no NetFx code changes in our library since 8.0.0 so you should be able to get all the latest updates with 8.0 with no need to upgrade your nuget client). 

Thanks again for reporting this,
Elham

**Comment by nitro52** [comment]
Thanks for the info, Idon't think there is any pressing need for us to upgrade to 8.1 at the moment, i'll keep this in mind when we do update next.
