### ISSUE TITLE
OutOfMemoryException on .NET Core when computing MD5 hash

### ISSUE THREAD

**Issue by cincuranet** [Azure/azure-storage-net#422]
OutOfMemoryException at

```
   at System.IO.MemoryStream.ToArray()
   at Microsoft.WindowsAzure.Storage.Core.Util.MD5Wrapper.ComputeHash()
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.<CommitAsync>d__9.MoveNext()
```

Looking at [that code](https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/Core/Util/MD5Wrapper.cs#L101) I see it's doing `ToArray` on the `MemoryStream` it is using.

With that I can't upload files of significant size without turning off the MD5 checksums.

**Comment by erezvani1529** [comment]
Hi @cincuranet,

Thanks for reporting this issue. You are right and you can use version [8.0.0 ](https://www.nuget.org/packages/WindowsAzure.Storage/8.0.0)of our library for the fix.

In 8.0 we updated the hashing code to use IncrementalHash implementation which was added to Netstandard1.3 and implemented in NetCore. However, we had to release a hotfix to revert that change temporarily, since Xamarin/Mono was not caught up on the implementation of Incremental Hash at that point(and this was causing blocking issues for our Xamarin Users).

Latest update from Xamarin (as of our follow up this morning) is that the fix will become available in near future so we will have the fix back again (hopefully) by our 8.2 release(by mid-March).

I will make sure to update this thread with latest updates, but you should be unblocked with version 8.0 as I mentioned.

Thanks,
Elham

**Comment by dabide** [comment]
Any news on this?

**Comment by erezvani1529** [comment]
Hi @dabide,

The fix for this particular feature will be provided once Mono 5.0 (stable) is released which will tentatively be sometime in May. 

Additionally, we are considering the option of adding a new target to our Nuget package for Xamarin/Mono to add tolerance for cases like this until NetStandard implementation on all platforms are stabilized.

Thanks,
Elham

**Comment by thomfre** [comment]
Any news on this now?

Mono 5.0 was released mid May.

**Comment by Porges** [comment]
Is this fix in 8.2? I can't see it mentioned in `changelog.txt`.

**Comment by erezvani1529** [comment]
@Porges, @thomfre,

Thanks for the follow up. This change is included in our next release which planned to be published in next 2 weeks. 

Thanks,
Elham

**Comment by Porges** [comment]
Thanks @erezvani1529
