### ISSUE TITLE
Documentation url appears broken

### ISSUE THREAD

**Issue by tommysundling** [Azure/azure-storage-net#445]
One of the first links in the documentation, "Getting Started" (http://azure.microsoft.com/en-us/documentation/articles/storage-getting-started-guide/) appears to be broken.

**Comment by erezvani1529** [comment]
Hi @tommysundling,

Thanks for reporting your issue. We are in the process of restructuring our documents and the above page has been removed due to some deprecated content(although it might appear in the search results for a while). Please refer to this [page](https://docs.microsoft.com/en-us/azure/storage/storage-dotnet-how-to-use-blobs) for the latest getting started information.

Thanks,
Elham
