### ISSUE TITLE
Incorrect unit test

### ISSUE THREAD

**Issue by arafato** [Azure/azure-storage-net#484]
Hi all, 

I've noticed that the unit test at https://github.com/Azure/azure-storage-net/blob/master/Test/ClassLibraryCommon/Blob/CloudBlobTest.cs#L314 is incorrect. It assumes that the HTTP headers used for meta properties (`such as x-ms-meta-<name>`) are case sensitive. According to http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2, however, HTTP headers are case insensitive. 
Can you fix this? Thanks!

**Comment by kfarmer-msft** [comment]
Hi, arafato -- Thanks for writing

We've looked at this, and note that the implementation is following our spec about case preservation (see https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata), which is why the unit test passes.  Given that this library targets specific servers, you may consider the fact that we encode the metadata using HTTP headers as an implementation detail.

Are you seeing the test fail when run against Azure?

**Comment by arafato** [comment]
@kfarmer-msft no all good. My mistake. Closing this issue.
