### ISSUE TITLE
Blob download API returning corrupted stream (transient issue)

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#488]
We have found a bug in storage service which could return corrupted stream from Blob download API. It happening like 1 /  1M operations. 

Technical details:

1.	All blobs in our service is immutable with new guid as name. Once written we share blob link and never modify.
2.	We use https with disabled UseTransactionalMD5 as recommended.
3.	Content internally is deflate compressed, so we decompress it before consuming it.
4.	Issue is manifested as 

exception: 'Unknown block type. Stream might be corrupted.'.
System.IO.InvalidDataException: Unknown block type. Stream might be corrupted.
   at System.IO.Compression.Inflater.Decode()
   at System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)

5.	We have built-in retry logic which will attempt to download content again and try to decompress it  again to compensate for this issue which almost always works on first attempt.

We have traces for failed and retry operations.

1.	Blob download which resulted in corrupted state

[{"startTime":"2017-06-12T12:02:44.1978532Z","endTime":"2017-06-12T12:03:32.4812659Z","etag":"\"0x8D4B18ADF0748D3\"","contentMd5":"MMAeC0vSsEV79u/dZg5Rfw==","httpStatusCode":200,"httpStatusMessage":"OK","serviceRequestID":"c0765c13-0001-0042-7573-e3c616000000","ingressBytes":5636096,"egressBytes":0},{"startTime":"2017-06-12T12:03:35.5439112Z","endTime":"2017-06-12T12:03:35.825166Z","etag":"\"0x8D4B18ADF0748D3\"","httpStatusCode":206,"httpStatusMessage":"Partial Content","serviceRequestID":"ad1eaf30-0001-00d4-2873-e3a422000000","ingressBytes":8313772,"egressBytes":0}]

2.	And immediate retry attempt which succeeded.

[{"startTime":"2017-06-12T12:03:36.9974827Z","endTime":"2017-06-12T12:03:37.4033609Z","etag":"\"0x8D4B18ADF0748D3\"","contentMd5":"MMAeC0vSsEV79u/dZg5Rfw==","httpStatusCode":200,"httpStatusMessage":"OK","serviceRequestID":"a1945f4d-0001-00cd-4973-e3884a000000","ingressBytes":13933484,"egressBytes":0}]

Few things to note:

1.	Both requests advertise same md5 and etag. 
2.	Sum of ingress bytes does not match.
3.	‘Failed’ download operation was spitted into 2 requests with partial content and took 50+ seconds which is unusual.
4.	‘Succeed’ download was able to complete in 1 requests under 500ms.

**Comment by congyiwu** [comment]
@erezvani1529 do you remember what the corruption may have looked like or if there's an easy repro?

We're experiencing very rare instances of downloaded blob corruption in our service as well w/ WindowsAzure.Storage.7.2.1/.  In one case for a ~1MB blob, the byte sequence from 0x3FDFA-0x3FFFF was repeated right after at 0x40000-0x40205.  The rest of the content was identical.  I.e. instead of abcdefgh, we saw abcd**cd**efgh

We're calling CloudBlockBlob.DownloadRangeToStream in 10MB chunks, so it seems suspicious that we'd see corruption on an exact 256KB boundary.  We plan on upgrading to 8.3 or newer to get this fix, but it would be good to verify ahead of time that we're hitting the same bug.

**Comment by erezvani1529** [comment]
Hi @congyiwu ,

What you have described sounds like the same issue we have fixed. The issue is a race condition in resume download logic during a retry where the last copy state position wasn't updated properly (due to some unhandled exception), so after the retry redundant data(the last write buffer) would be re-copied to the output stream.

Please make sure to checkout the [changelog](https://github.com/Azure/azure-storage-net/blob/master/changelog.txt)/[BreakingChangesList ](https://github.com/Azure/azure-storage-net/blob/master/BreakingChanges.txt)before upgrading to 8.0.

Thanks!
