### ISSUE TITLE
Change leased lease, with idempotent change

### ISSUE THREAD

**Issue by arafato** [Azure/azure-storage-net#496]
Hi all, 

I'm currently looking at the lease semantics of containers and I'm confused about the following unit test at https://github.com/Azure/azure-storage-net/blob/master/Test/ClassLibraryCommon/Blob/LeaseTests.cs#L6463-L6468

Why is it that https://github.com/Azure/azure-storage-net/blob/master/Test/ClassLibraryCommon/Blob/LeaseTests.cs#L6468 does not result in an exception? The active leaseId is first changed to `proposedLeasedId2` in line 6466. Then in line 6468 `x-ms-lease-id` is again set to `leaseId` where it should be `proposedLeasedId2` (we just changed the active lease id from `leaseId` to `proposedLeaseId2`. So why is line 6468 not like 
`leaseId2 = leasedContainer.ChangeLease(proposedLeaseId2, AccessCondition.GenerateLeaseCondition(leaseId2));`

Any help is really appreciated, thanks!
Best regards
--Oliver.

**Comment by pemari-msft** [comment]
This is actually a good question. /cc @rickle-msft, can you check?

**Comment by mirobers** [comment]
Changing a lease is idempotent on the service by design. If you are trying to change the lease to a value that is already the current lease ID then the request succeeds no matter what lease ID is passed as a condition. This is shown in one of the tables in the [Lease Blob REST API docs](https://docs.microsoft.com/en-us/rest/api/storageservices/lease-blob). See the table titled "Outcomes of lease operations on blobs by lease state" with row heading "Change, B to A". In the Leased(A) state, this request succeeds.

As for why the service does this, it is to handle the case where a change lease request times out on the client but commits on the service. Then the client can simply retry the request, see it succeed, and be sure that they hold the correct lease.
