### ISSUE TITLE
Requests not going through WebRequest.DefaultWebProxy

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-storage-net#534]
When working with storage queues, on .NET full framework all the requests are going through `WebRequest.DefaultWebProxy`. When working with .NET Standard version, they aren't. 

1. Is that by design?
1. What would be a unified way to optimally control if request should succeed or fail for unit testing? My current workaround is to use `OperationContext.GlobalSendingRequest`.

**Comment by erezvani1529** [comment]
Hi @SeanFeldman,

1. `WebRequest.DefaultWebProxy`  is not supported by NetCore (although it has been added to the backlog as a back-compat feature). Please see the corresponding [issue ] (https://github.com/dotnet/corefx/issues/7037) on CoreFx repo.

2. We recommend to move away from the GlobalEvents on the operation context in general. Is there a way to use the instance level SendingRequest event as a solution? Also, since we are working on a single HttpClient-based code-base, we may consider providing hooks into the HttpClientHandler properties such as the Proxy (we will announce decisions about this on separate issues in this repo once they are finalized).

Thanks,
Elham

**Comment by SeanFeldman** [comment]
@erezvani1529 thank you for the answer.

If I read it correctly, `WebRequest.defaultWebProxy` is not supported by .NET Core and you're suggesting to move away from `GlobalEvents`. Unfortunately, using instance level SendingRequest event is not an option. Which leaves me stuck with the leaser of two evils, `GlobalEvents` to get my tests working and no option to track an issue about `HttpClientHandler.Proxy` 😞 

Any chance to raise a tracking issue and label it as "in-review" so that it would be possible to subscribe and track changes w/o manually sipping through issues? It's a common practice on GitHub 🙂

Thank you.

**Comment by SeanFeldman** [comment]
@erezvani1529 with https://github.com/dotnet/corefx/issues/7037 been completed, is there an associated Storage issue to track?
