### ISSUE TITLE
how to get azure storage table  data in chunks

### ISSUE THREAD

**Issue by souvikneogi** [Azure/azure-storage-net#538]
I am trying to fetch data from Azure Storage Table in chunks. 
We need to show logs in a table which has paging. The logs are getting stored in Azure storage table.
As the volume of logs will be very high, so we need to fetch the data in chunks and show into a table.
We have trying it with TAKE(), but there is no way to understand the starting index of the next chunks.
We have tried with below code but there is no way to find the starting index of the next chunk.

var table = tableClient.GetTableReference(GetStorageTable(partitionKey));
var pkFilter = TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, partitionKey);
var combinedFilter = pkFilter;
foreach (var properties in propertyFilters)
                {
                    var newFilter = TableQuery.GenerateFilterCondition(properties.Key, QueryComparisons.Equal, properties.Value);
combinedFilter = TableQuery.CombineFilters(combinedFilter, TableOperators.And, newFilter);
                }

var query = new TableQuery<T>().Where(combinedFilter).Take(10);
                results = table.ExecuteQuery(query).ToList();

**Comment by ryanerdmann** [comment]
In order to retrieve paginated segments of results from the table service, you should use the `ExecuteQuerySegmented` API instead of `ExecuteQuery`.  This will return a `TableQuerySegment`, which will have a continuation token you can use to read the next page of results, as well as the list of results for that page.

You'll want to replace the last line of your code above with something like the following:

```
TableContinuationToken continuationToken = null;
do
{
    TableQuerySegment<DynamicTableEntity> segment =
        await table.ExecuteQuerySegmentedAsync(query, continuationToken);

    continuationToken = segment.ContinuationToken;

    Console.WriteLine($"Retrieved {segment.Results.Count} items.");
} while (continuationToken != null);
```

[[Docs]](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-dotnet#retrieve-entities-in-pages-asynchronously) [[Sample Code]](https://gist.github.com/ryanerdmann/63f832fdf21b80f69bdc55fcdaa964e8)

One final note: for scenarios where you are only appending data (common when working with logs), also consider using [Append Blobs](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-append-blobs), which are optimized for this pattern.
