### ISSUE TITLE
ETA on async support?

### ISSUE THREAD

**Issue by raRaRa** [Azure/azure-storage-net#542]
Any ETA on when the OData dependency will be removed and true asynchronous support will be added? This is already causing a lot of performance issues for many users, especially for those who need to do a lot of reads and writes to Azure Storage.

I had to write my own Azure Storage table client in order to overcome the issue of all my threads waiting for synchronous operations that happen inside OData, but I'd rather use the SDK as soon as there's true asynchronous support. I would love to hear if there are any plans to do it by the end of this year.

Thanks.

**Comment by erezvani1529** [comment]
Hi @raRaRa,

The OData removal task is done and undergoing internal preview and testing. This change will be released as a preview package containing only Table APIs (since it is bundled with the change to split the libraries into separate services).

There will be an announcement with more details about the timeline and what changes to expect. We will update the relevant issues on GitHub once the announcement is out. 

Thanks,
Elham

**Comment by pemari-msft** [comment]
Tracked by existing item (#457)
