### ISSUE TITLE
Buffer Reuse in Blob Storage SDK

### ISSUE THREAD

**Issue by smflorentino** [Azure/azure-storage-net#557]
We process millions of block BLOBs per day. Doing some perf optimizations on a new service I noticed that CloudBlob.DownloadToStreamAsync is not using IBufferManager, it is using AsyncStreamCopier which allocates two 64KB byte buffers:
https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Core/Util/AsyncStreamCopier.cs (line 252-253)
 
CloudBlob.DownloadToStream uses StreamExtensions, which also allocates a 64KB buffer:
https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/Core/Util/StreamExtensions.cs (line 82)
 
Interestingly, CloudBlob.OpenRead actually uses BlobReadStream, which in turn uses MultiBufferMemoryStream, which uses IBufferManager:
https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Blob/CloudBlob.cs (line 53)
 
 
My question is, why doesn’t DownloadToStream support buffer reuse. Are there any drawbacks from switching our service from DownloadToStreamAsync() to OpenRead() + Copy?

**Comment by erezvani1529** [comment]
Hi @smflorentino,

Thanks for reporting your issue. This item is on our backlog. Here is the [issue ](https://github.com/Azure/azure-storage-net/issues/362) tracking it and we will be prioritizing this item in our planning.

Back to your question, since there are differences between OpenRead and DownloadToStream, it depends on what your scenarios are. For instance if you have many small files, DownloadToStream* API would be a better choice since currently OpenRead makes a head call to fetch attributes and lock the stream on the blob's Etag for its lifetime so it might be considered less efficient in that case. 

Please let me know if you have a more specific scenario so that we can discuss further.

Thanks,
Elham

**Comment by danielmarbach** [comment]
There is also https://github.com/Azure/azure-storage-net/pull/543 by my friend @scooletz

**Comment by kfarmer-msft** [comment]
We made changes in v9.0 that should have affected this.  Please reopen if you still see these issues.
