### ISSUE TITLE
WindowsAzure.Storage 8.5.0.0: TableQuerySegment non-generic not available in net45, causing runtime exception

### ISSUE THREAD

**Issue by NicolasDorier** [Azure/azure-storage-net#562]
Imagine you have AwesomeLib which target netstandard1.3, and use non generic TableQuerySegment.

AwesomeApp which targets .net 4.6.2 references AwesomeLib. Because of how nuget works, AwesomeApp will resolve net45 lib of WindowsAzure.Storage.

But because net45 does not have non generic TableQuerySegment, you will have a runtime exception thrown when AwesomeLib is called.

**Comment by erezvani1529** [comment]
Hi @NicolasDorier ,

Thanks for bringing up your issue. We have already discussed this on another thread (issue #416).
Is there a reason that the generic query segment class will not work for you?

Thanks,
Elham

**Comment by NicolasDorier** [comment]
I have no issue with non-generic not being support.

This issue is about having runtime exception thrown because netstandard1.3 falsely make you believe that the non-generic version is available on all netstandard1.3 supporting runtime when it is not the case.

**Comment by erezvani1529** [comment]
Thanks @NicolasDorier,

The change you have mentioned is already in progress as part of our plan to unify the code-bases in an effort to support Netstandard2.0 and provide full feature parity between Desktop and RT/NetCore code-bases. 
As for your point about netstandard1.3 support, our library has a net45 target which as you have mentioned will be picked in a NetFX target over netstandard1.3 which is expected according to [this table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) since the minimum netfx version supported by netstandard1.3 is 4.6.

Thanks,
Elham

**Comment by NicolasDorier** [comment]
Given 461 does not support netstandard20, this problem will not be fixed for 461 clients using this package though.

**Comment by erezvani1529** [comment]
Apologies if I was not clear. This problem will be fixed when the Desktop code-base is used for all targets (which is happening as part of Netstandard2.0 support and feature parity task).

Will keep this issue open to notify once the related changes are out.

Thanks,
Elham

**Comment by alex-zyl** [comment]
I'm facing similar issue running Asp.net core 2.0 project (TF = netcoreapp2.0) that has a dependency on ne461 project. 
Both projects are referencing WindowsAzure.Storage;  net461 project calls QueueClient.CreateIfNotExists method that exists in net45 assembly, but missing in netstandard1.3. This causes runtime error MissingMethodException as compiler resolved WindowsAzure.Storage.dll to use netstandard1.3 version

**Comment by erezvani1529** [comment]
Hi,

This issue is fixed for [Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/9.4.0-preview), [Queue ](https://www.nuget.org/packages/Microsoft.Azure.Storage.Queue/9.4.0-preview)and [File ](https://www.nuget.org/packages/Microsoft.Azure.Storage.File/9.4.0-preview)in our preview split packages with Netstandard2.0 target. Please make sure to review the BreakingChanges lists on the nuget packages before you use them.

Since the release of CosmosDB Table sdk [package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/), 
support for Table service has transitioned to CosmosDB team. The CosmosDB team has planned support for Netstandard2.0.  Please email the team at : `askcosmosdbtableapi@microsoft.com` for more information. 

Thanks!
