### ISSUE TITLE
CloudFileDirectory.ListFilesAndDirectories Missing

### ISSUE THREAD

**Issue by clockwiseq** [Azure/azure-storage-net#583]
8.5.0 (for .NET Framework) exists

8.5.0/8.6.0 (for .NET Core) missing

any help would be greatly appreciated.

**Comment by erezvani1529** [comment]
Hi @clockwiseq,

The library provides the method ListFilesAndDIrectoriesSegmented method in the NetCore target instead of the sync method (our NetCore target is Async only). Below is a sample of how to call the segmented method to list files in a directory for instance:

           ` FileContinuationToken token = null;
            do
            {
                FileResultSegment resultSegment = await  sampleDir.ListFilesAndDirectoriesSegmentedAsync(token);
                token = resultSegment.ContinuationToken;

                foreach (IListFileItem listResultItem in resultSegment.Results)
                {
                    listedFileItems.Add(listResultItem);
                }
            }
            while (token != null); `


Please let us know if you have any other questions. 

Thanks,
Elham
