### ISSUE TITLE
v9.0.0 exception: Microsoft.WindowsAzure.Storage is deployed incorrectly

### ISSUE THREAD

**Issue by voyager18** [Azure/azure-storage-net#628]
I've updated the assembly from 8.7.0 to 9.0.0 and running the application I've this error

Microsoft.WindowsAzure.Storage is deployed incorrectly. Are you missing a Table Service assembly (Microsoft.Data.Services.Client, Microsoft.Data.OData or Microsoft.Data.Edm) or a related binding redirect? ---> System.TypeLoadException: Could not load type 'Microsoft.WindowsAzure.Storage.Table.DataServices.TableServiceContext' from assembly 'Microsoft.WindowsAzure.Storage, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

Downgrading to 8.7.0, all works perfectly.

**Comment by mirobers** [comment]
TableServiceContext has been deprecated since version 4.0 and was removed in version 9.0 as part of dropping OData dependencies. See the [Breaking Changes](https://github.com/Azure/azure-storage-net/blob/master/BreakingChanges.txt). If you have a dependency that relies on it then you will need your dependency to upgrade to version 9.0 (or better yet, migrate to the [CosmosDB table library](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/)).

We will also be releasing split packages for 9.0 for blob, queue, and file soon, so you can use those to get 9.0 features without having to take table-related changes.

**Comment by corneliutusnea** [comment]
Sadly the Microsoft.Azure.WebJobs requires the WindowsAzure.Storage so upgrading this package breaks the webjobs with the above error message.

**Comment by charlesw23** [comment]
Thanks Folks!  This Comment saved me some time!

**Comment by mhectorgato** [comment]
- File->New WebJob
- Updated all NuGet to current versions
- Added Microsoft.Azure.WebJobs.ServiceBus 

Am getting this same error.

**Comment by toenners** [comment]
Any resolution to this?

**Comment by erezvani1529** [comment]
As @corneliutusnea  metioned, this is a WebJobs dependency issue and is currently being tracked by WebJobs issue [#1571](https://github.com/Azure/azure-webjobs-sdk/issues/1574) and looks like there is [PR ](https://github.com/Azure/azure-webjobs-sdk/pull/1575) out as a fix already.

Closing this to avoid confusion for folks who are redirected to this issue.

Thanks!
