### ISSUE TITLE
"Use RequestResult.ErrorCode instead"

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#629]
Why ErrorCode was marked as obsolete? Why introduce breaking change for such minor detail?

I am working on a library which depends on Azure storage library and today consumers of my library are free to choose any version 6.x to 8.x version to link (with assembly redirect). Now I would need to use new property making it impossible for consumer of my library to use any version < 9.0

Storage team, why introduce breaking change for such minor detail? Is any functional issue with it? Looks like pretty unnecessary cosmetic change. 

Storage team I urge you to correct this nonsense with 9.0.1 release:
1. Remote Absolute attribute.
2. Keep the ErrorCode property on RequestResult but let it be a proxy for (RequestInformation.ErrorCode)

**Comment by IlyaGrebnov** [comment]
New property is also regressed for important scenario. 

        static void Main(string[] args)
        {
            try
            {
                var account = CloudStorageAccount.DevelopmentStorageAccount;
                var table = account.CreateCloudTableClient().GetTableReference("test");

                var batch = new TableBatchOperation();
                batch.Add(TableOperation.Insert(new DynamicTableEntity("A", "A")));

                table.CreateIfNotExists();

                table.ExecuteBatch(batch);
                table.ExecuteBatch(batch);
            }
            catch (StorageException ex) when (ex.RequestInformation.ErrorCode == "EntityAlreadyExists")
            {
                // you won't hit this line, because ErrorCode is null. 
            }
        }

**Comment by rezvanel** [comment]
Hi @ilyagrebnov,

Thank you for the feedback and reporting the bug.  We have decided to remove the deprecated property for table because of a special behavior on the server side for now.

Planning to publish this change aling with a few more fixes from public dev, next week.

**Comment by erezvani1529** [comment]
@IlyaGrebnov ,

Thank you for the feedback and reporting the bug. We have decided to remove the deprecated property due to a special behavior on the server side (specific to tables).

Planning to publish this change along with a few more fixes from public dev, next week.

Thanks,
Elham

**Comment by IlyaGrebnov** [comment]
If this is issue with just table server why not fix just table server? Why impact client and introduce breaking change for such minor detail? Is any functional issue with it? Looks like pretty unnecessary cosmetic change. 

This is wrong decision. I am telling you as member of "Azure API Review Board".

**Comment by erezvani1529** [comment]
Apologies if I was not clear enough. I meant the regression(bug) you reported is specific to table service and we have decided to remove the "obsolete" tag for now with a release next week.

Also for clarification, the ErrorCode is added to the RequestResult mainly due to requests by many users who complained about the discoverability of it. (cc: @seguler )

Hope this clears the confusion.

Thanks,
Elham

**Comment by bigtfromaz** [comment]
So...does this code return true when a query returns no entities?

 try
            {
                query = await table.ExecuteAsync(retrieveOperation);
            }
            catch (StorageException ex)
            {
                if (ex.RequestInformation.ErrorCode.Equals("ResourceNotFound"))
                {
                    return null;
                }
                else throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }

**Comment by isaacabraham** [comment]
We've also just noticed this. Is there an issue to track the specific bug i.e. `ErrorCode` is not populated for batch operations?

**Comment by erezvani1529** [comment]
@IlyaGrebnov , please upgrade to v9.1 package for an update where the ErrorCode property on StorageExtendedErrorInformation is not a deprecated property anymore. 

@isaacabraham , @bigtfromaz , the issue is that the ErrorCode property on RequestResult will not be populated by service for any Table operations involving OData. You should be able to use the existing ErrorCode on ExtendedErrorInformation as before with v9.1 since we have reverted the deprecation of this property.

Please do not hesitate to re-open if you have any other issues.

Thanks!
