### ISSUE TITLE
Is it possible to tell if CloudQueueMessage contains string vs byte array?

### ISSUE THREAD

**Issue by Jericho** [Azure/azure-storage-net#631]
When fetching a message from an Azure queue is there a way to know if the message was added as a string or as an array of bytes?

In my scenario it's important because I treat byte array differently than I do strings. Here's what I currently have:

```csharp
var content = (object)null;
try
{
    content = cloudMessage.AsString;
}
catch
{
    content = Deserialize(cloudMessage.AsBytes);
}
```

This code relies on the fact that retrieving the content as a string throws an exception. This assumption is true in my scenario because the serialized binary content can't be converted back into a string. As you can imagine I don't like to rely on an exception being thrown, especially since the vast majority of the messages I fetch from the azure queue contain binary data.

What I'm looking for is to be able to do something like (pseudo-code):

```csharp
var content = (object)null;
if (cloudMessage.ContainsBinary)
{
    content = Deserialize(cloudMessage.AsBytes);
}
else
{
    content = cloudMessage.AsString;
}
```

**Comment by erezvani1529** [comment]
Hi @Jericho,

You are right **not to** rely on `.AsString` to throw since when the message is being created(via either binary or string overloads) the client library handles the encoding depending on the `EncodeMessage `property on your queue. By default we assume the string returned from server is Base64 encoding of the original message (`EncodeMessage `is by default set to `true`).
If this field is not set to true, exception is likely to be thrown but the users need to make sure the `EncodeMessage `setting matches the queue that is being read.

**Comment by Jericho** [comment]
I am glad you understand what I'm saying and agree that I shouldn't rely on `.AsString` throwing an exception. But what's my alternative? 

In my scenario, there are multiple third party processes adding messages to a given Azure queue and I am responsible for the process that fetches the messages from the queue. When I get a message, how can I determine if they added a byte array or a string?

**Comment by Jericho** [comment]
In case I'm not being clear, what I'm trying to achieve is to be able to differentiate between:

__Scenario 1__: 
The message contains a string: 

```csharp
var cloudMessage = new CloudQueueMessage("Hello World");
await _queue.AddMessageAsync(cloudMessage).ConfigureAwait(false);
```

In this scenario I need to get the string content like so: 
```
var cloudMessage = await _queue.GetMessageAsync().ConfigureAwait(false);
var content = cloudMessage.AsString;
```

__Scenario 2__
The message contains an array of bytes: 

```csharp
var cloudMessage = new CloudQueueMessage(string.Empty);
cloudMessage.SetMessageContent(new byte[] { ... });
await _queue.AddMessageAsync(cloudMessage).ConfigureAwait(false);
```

In scenario 2 I need to get the binary content like so: 
```
var cloudMessage = await _queue.GetMessageAsync().ConfigureAwait(false);
var content = cloudMessage.AsBytes;
```

Unfortunately, as far as I can tell, there is no way to distinguish between the two.

**Comment by J0rgeSerran0** [comment]
The same here.
I'm using AddMessage to include binary messages and text messages.
I'm using GetMessage to get a message.

But when I get a message, I don't know really if the message is a binary or text message.

When I use AsByte for both scenarios, I get the bytes of a message (binary or string).
But when I use AsString and the message is binary, the AsString returns the next info:

'cloudQueueMessage.AsString' threw an exception of type 'System.Text.DecoderFallbackException'

It would be very interesting to have a flag IsBinary (for example) in the CloudQueueMessage object to know if the message has a binary content or not.

At the moment, I have resolved this with a work around, but for me has sense to include this property in the CloudQueueMessage object to avoid to add dirty code in the process.

**Comment by diggity-dan** [comment]
I have a similar issue where analyzing queues is part of a monitoring strategy. The application relies heavily on azure queues (not my design, unable to change this).

Parsing message data and deriving any meaning from it using the peek methods is very cumbersome because you have no idea about the format in which the message data is stored. Some data is XML, some is plain string data, etc...

In order to read the message and perform analysis/monitoring of any kind leads to relying on exceptions when performing type conversions/casting and tons of checks and balances all over the code.

It would be great to have a message format property on the message its self, so you can reliably determine what it is. Not just for string or bytes, but for all data types.

**Comment by seanmcc-msft** [comment]
Hi everyone,

Unfortunately, there is currently no way to determine the content type of messages without potentially throwing an exception.  I've contacted our back end service team, and submitted a request to potentially enable this feature in the service in the future.

-Sean

**Comment by codingoutloud** [comment]
I realize it may not be ideal and introduces other complexities, but one option is to have different queues with different message contracts - e.g., distinct `widgetqueue-bytearray` and `widgetqueue-object` queues.
