### ISSUE TITLE
Query on encrypted column doesn't work

### ISSUE THREAD

**Issue by lzc850612** [Azure/azure-storage-net#633]
I'm using Azure storage and i'm wring a query like:
var query = from DataEntity in tableQuery
                                where DataEntity.PartitionKey == partitionKey &&
                                        DataEntity.A== "a" &&
                                        DataEntity.UserId == "randomstuff"
                                select DataEntity;

the PartitionKey and A columns are non-encrypted column, while the UserId column is ecrypted column. When I'm running this query, i couldn't get any data back. When I remove the 'DataEntity.UserId == "randomstuff"' condition, the query can return some data. and in that record, the UserId property has exactly the same value as "randomstuff". This makes me think, is the Azure Storage client library not working well with an encrypted column? if it works well, why would it not return any record when the UserId condition is actually met? Is there some kind of bug when running a query which has encrypted column in the condition clause?

**Comment by maxpert** [comment]
Same issue here!

**Comment by erezvani1529** [comment]
@lzc850612 ,

Would you please share your code sample? Are you passing an encryption policy to your ExecuteQuery operation?

**Comment by erezvani1529** [comment]
We had a discussion with @maxpert internally given their code sample; updating with the results:

"You are filtering server-side on the ciphertext, which can’t work because each matching row has a unique IV that is impossible to know without first fetching the rows. It would be a security concern if you could perform such an operation server-side, in fact, because it would reveal without the encryption key which rows share the same value of an encrypted column.
 
A quick fix is to do the `where` filtering client-side for each segment retrieved, so you fetch, decrypt, and compare in that order. In your code, this could be done with LINQ on the `entities` variable instead of the IQueryable.
"
@lzc850612 , if you are also using IQueryAble please follow the recommendation above to solve your problem. Do not hesitate to re-open the issue if you are still facing issues.

Thanks!
