### ISSUE TITLE
WindowsAzure.Storage not supported by Microsoft.Fakes framework.

### ISSUE THREAD

**Issue by Kressilac** [Azure/azure-storage-net#669]
![image](https://user-images.githubusercontent.com/28730391/38579979-b604c6a4-3cd6-11e8-8deb-66372ba8514c.png)

When adding WindowsAzure.Storage to the unit test project and attempting to add a Fakes assembly from it, Visual STudio reports that the assembly does not support Microsoft.Fakes.  Is this intentional?  If I use the older packages.config method of managing NuGet packages instead of Package References and NuGet 4.0+, I can fake the package just fine.  After upgrading to Package Reference, I can no longer do this.

![image](https://user-images.githubusercontent.com/28730391/38580107-1c7aa49e-3cd7-11e8-85c6-d10d16a94ff2.png)

If this is no longer supported then the following article should be considered deprecated and I need a new method for isolating Azure Storage calls in my unit tests.  Perhaps everything in the DLL is properly interfaced and I can use Moq?

https://social.technet.microsoft.com/wiki/contents/articles/35320.faking-out-azure-unit-testing-with-microsoft-fakes.aspx

Thanks
Derek

**Comment by veleek** [comment]
This still appears to be an issue.  If I attempt to create a Fakes assembly for an assembly that's located in a PackageReference'd project, it will fail, and if you right click on an individual assembly within that package, the right click menu doesn't have an option to generate a fake at all.

![image](https://user-images.githubusercontent.com/1055021/53767675-580af480-3e8b-11e9-980c-cee8fc278869.png)

**Comment by kfarmer-msft** [comment]
Does this happen with all packages, or just the storage packages?

**Comment by veleek** [comment]
In digging into this a bit more, it turns out that this is just a general issue with the new .csproj format.  Fakes are not supported with it (https://github.com/dotnet/project-system/blob/master/docs/feature-comparison.md).  

It looks like lots of people end up going down this route because the Azure storage documents suggest using it as an option for testing.  As @Kressilac suggested, maybe the documentation in question needs to be updated.
