### ISSUE TITLE
V9.1.1 Large CPU usage increase for Table storage operations

### ISSUE THREAD

**Issue by antross** [Azure/azure-storage-net#671]
After upgrading from V9.1.0 to V9.1.1 we noticed a large increase in our CPU usage on our .NET-based Azure Web Apps when performing table storage operations (mostly reads and deletes). Web jobs which previously used ~20% CPU on a small instance started spiking between 80-100% and took almost twice as long to complete. It's unclear if Blob and Queue operations were similarly affected as they were not part of these jobs.

Rolling back to V9.1.0 resolved the issue for the time being, but we'd of course like to figure out how to fix this so we can get back on the latest version.

**Comment by gorgi** [comment]
I noticed the same thing for updating from 8.7.0. The load time increased 3 times for loading 30 000 entities. I rolled back to 9.1.0 and the loading time is back to normal.

**Comment by ajorkowski** [comment]
I'm seeing the same thing... Looking at the code changes for 9.1.1 I would say the issue is in the `TableOperationHttpResponseParsers.ReadSingleItem` method. EVERY item uses a new serializer (via `DefaultSerializer.Create()`) which I think would cause issues with read requests with lots of items.

I think the serializer should probably be created once and re-used to prevent this issue.

**Comment by mirobers** [comment]
Thank you all for the report. We are working on a fix. @kfarmer-msft

**Comment by GrzegorzBlok** [comment]
I can confirm that this issue is still occurring in 9.2.0.

**Comment by hami89** [comment]
We experienced the same issue with v9.x SDK version. Is the issue still occurring in v9.3.0?

**Comment by gorgi** [comment]
We tested out 9.3.0 and the issue is gone.
