### ISSUE TITLE
I can't seem to find much documentation around AuthenticationFailed/Request forbidden

### ISSUE THREAD

**Issue by Maqsoodp** [Azure/azure-storage-net#675]
We are running a Data factory to copy huge data (>100GB) from one coldstore to another obviously with some transformation. We have noticed that the Datafactory logs 403 Forbidden error intermittently (approx few hundred times) when called following

` await blockBlob.UploadFromStreamAsync(ms, AccessCondition.GenerateEmptyCondition(), blobRequestOptions, null);`

I cloned this library to figure out any Test case around 403 , but can't seem to find one.

Here is my BlobrequestOptions

` var blobRequestOptions = new BlobRequestOptions() { 
MaximumExecutionTime = TimeSpan.FromMinutes(60), 
ServerTimeout = TimeSpan.FromMinutes(60), 
RetryPolicy = new LinearRetry(TimeSpan.FromSeconds(5), 5) };`

Error -

> 
Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.

StatusMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ErrorCode:AuthenticationFailed

**Comment by mirobers** [comment]
There are a few sources of authn failures:
* You could be using the wrong account key, or a corrupt SAS token.
* The request will fail authentication if its Date header is more than 15 minutes in the past. (In other words, the request was delayed by 15 minutes or the system clock is off.)
* Your SAS token could have expired or it could have been revoked.

The storage exception contains extended information including details that can help narrow down what the issue is.
