### ISSUE TITLE
BlobEncryptionPolicy gone from .Net?

### ISSUE THREAD

**Issue by BradleyDHobbs** [Azure/azure-storage-net#680]
[Client-Side Encryption and Azure Key Vault for Microsoft Azure Storage](https://docs.microsoft.com/en-us/azure/storage/common/storage-client-side-encryption?toc=%2fazure%2fstorage%2fblobs%2ftoc.json)

BlobEncryptionPolicy seems to be missing from the latest azure storage nuget packages, yet their documentation and code samples still reference it.

If it was removed, what is the new way of using client side encryption in .NET?

**Comment by PlaidPhantom** [comment]
I'm running into this as well. Has something changed?

**Comment by PlaidPhantom** [comment]
Okay, on further investigation, I rebuilt my library project as a .NET Framework library instead of a .NET Standard or .NET Core library and this seems to have fixed my problem.  Is this not a supported combination? @BradleyDHobbs could you try this and see if you see the same behavior? I made a new project, copied my code over, and added the appropriate Nuget packages and it all seemed to compile.

**Comment by mirobers** [comment]
That is correct. The netstandard package does not support encryption (and never has). Unfortunately, this impacts netstandard 2.0 packages. We are about to release netstandard 2.0 support in preview, which will resolve this issue. Until then, explicitly targeting .NET Framework is the right workaround.

**Comment by malikou** [comment]
still having this problem.  I am porting a web api application to .net core and BlobEncryptionPolicy is core feature that I cannot do without.  Sounds like this functionality became available in .Net standard 2.0 preview but I am not sure how to access the functionality.  Thanks for your help
