### ISSUE TITLE
Azure Storage Emulator v5.5 - Unable to start the storage emulator

### ISSUE THREAD

**Issue by ry8806** [Azure/azure-storage-net#704]
Apologies if this is the wrong place to file this bug, I've been looking for a location for the last 30 mins and this is the "best/nearest" I can find.

I've just downloaded the latest version of the storage emulator (v5.5) and can't get it to run. The following error appears:

![image](https://user-images.githubusercontent.com/10958000/40836819-171b0782-6590-11e8-8590-2a40e8ebeb3b.png)

I can't find any logs in the install directory for the emulator (C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator)

I've also uninstalled, removed db in LocalDb (manual), restarted and installed. Still no luck.

Is the plan from MS to start moving over to Azurite(https://github.com/azure/azurite) as it's open source and seems pretty solid?

One other note..... I can't Debug Functions through Visual Studio without having the "Azure Storage Emulator" activated - feels a bit preventative when it doesn't work and I could use Azurite

Cheers

**Comment by mirobers** [comment]
Could you try the following command?

`AzureStorageEmulator.exe start -inprocess`

This will echo more information to the command line.

Regarding Azurite, yes, we recommend migrating to it if possible. Visual Studio support is on its roadmap.

**Comment by ry8806** [comment]
thanks, i've seen this on a colleagues machine earlier too - will try that command when i'm in the office tomorrow and also make sure there's no weirdness with the way the machines are configured too

**Comment by ry8806** [comment]
@mirobers 

I've just ran the command you gave and it's saying that "Access is denied", I think it's machine policy that's getting in the way. I have been able to run Azurite locally - so not sure what exactly the policy is blocking.

I'll take your advice and start getting our dev team to move to Azurite

Thanks so much for your help. Ryan

**Comment by ScottyMacDev** [comment]
Hi, I am actually running into this issue now as well. Here is what I have so far:

C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>AzureStorageEmulator.exe init /forceCreate
Windows Azure Storage Emulator 5.4.0.0 command line tool
Found SQL Instance (localdb)\MSSQLLocalDB.
Creating database AzureStorageEmulatorDb54 on SQL instance '(localdb)\MSSQLLocalDB'.

Granting database access to user TVI\smcintosh.
Database access for user TVI\smcintosh was granted.

Initialization successful. The storage emulator is now ready for use.
The storage emulator was successfully initialized and is ready to use.

C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>AzureStorageEmulator.exe start -inprocess
Windows Azure Storage Emulator 5.4.0.0 command line tool
Service Status: Blob http://127.0.0.1:10000/ False
The process cannot access the file because it is being used by another process
Error: Unable to start the storage emulator.

**Comment by cliptaak** [comment]
the trick is to run it in an elevated command prompt.
Right click on your cmd or powershell and select 'run as administrator'
Once you start the emulator manually, visual studio will work with just fine. I know there is a setting in visual studio to use elevated privileges, but don't remember where...

**Comment by cliptaak** [comment]
in fact you can simply start visual studio with "run as administrator" 
you'll have to turn off the compute and storage emulators and let VS start it for you

**Comment by superyyrrzz** [comment]
> The process cannot access the file because it is being used by another process

I met the same error as @ScottyMacDev, and resolved it with [this answer on SO](https://stackoverflow.com/questions/6415284/windows-azure-development-storage-blob-service-not-starting#answer-8731631).

**Comment by GaetanoSiano** [comment]
Had the same issue, deleting the AzureStorageEmulatorDb510* files in my user folder(C:\Users\{UserName}) and running C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>AzureStorageEmulator.exe init /forceCreate solved it for me. I was then able to start with AzureStorageEmulator.exe start.
Also ran the Cmd.exe in administrator mode.
