### ISSUE TITLE
It can take 5 minutes to receive a 429 (or other result)

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-storage-net#705]
I'm using Cosmos DB Table API with the old table storage sdk because https://github.com/Azure/azure-documentdb-dotnet/issues/344

Perhaps the issue belongs here instead of where I first posted it: https://github.com/Azure/azure-documentdb-dotnet/issues/517 - because the problem seems to be client-side and this repo is for the client I'm using.

Short version.
- Post 10k retrieves by PK/RK
- Sometimes:  5 minutes later, a 429 error
- Sometimes:  5 minutes later, an error with status code 0
- In one instance, await Table.ExecuteAsync(TableOperation.Retrieve("aaaa", "bbbb")); didn't return for over 10 hours until I disabled the network adapter in control panel, after which it instantly returned.

**Comment by mirobers** [comment]
For the really long requests, you can set a MaximumExecutionTime in your request options to make it error out sooner on the client.

Otherwise, this looks like a request to CosmosDb. Azure Storage doesn't return 429 and the request ID in your screenshot in the other issue isn't the right format for Azure Storage either. The other issue is the right place to follow up on this.
