### ISSUE TITLE
Emulator upgrades should not nuke the existing database of blobs etc

### ISSUE THREAD

**Issue by Plasma** [Azure/azure-storage-net#744]
### Which service(blob, file, queue, table) does this issue concern?
Storage Emulator

### Which version of the SDK was used?
5.6

### Which platform are you using? (ex: .NET Core 2.1)
n/a

### What problem was encountered?
Whenever we upgrade to a new storage emulator version, our existing blobs in the emulator for local development get deleted. This is painful because now local data is lost and needs to be re-created.

### How can we reproduce the problem in the simplest way?
Just upgrade from one version to another.

### Have you found a mitigation/solution?
Avoid upgrading.

**Comment by xt0rted** [comment]
I don't think the data is actually deleted, I think it creates a new dB next to the old one that's used for the new version of the emulator.

This is the reason I started moving over to [Azurite](https://github.com/Azure/Azurite), because with that I can tell it to store everything in my project folder so if I update to a new version all of my data is persisted (also lets me have a storage environment per project). The only issue I've had with Azurite is the lack of table storage support right now, but for blobs & queues it's been working great.

**Comment by mirobers** [comment]
This is by design. When the database schema changes, no data migration is supported. We solve this by using a new database for each version. Migrating to Azurite is a good suggestion; it gives you more flexibility.
