### ISSUE TITLE
Improve error message when dealing with duplicate partition-/rowkey items in batch

### ISSUE THREAD

**Issue by ErikSchierboom** [Azure/azure-storage-net#83]
When you try to execute a batch in which there are two items with the exact same partition key and row key, the library throws the following exception:

```
Additional information: Unexpected response code for operation : 1
``` 

This exception does not really disclose what went wrong. Perhaps it would be better to show something like:

```
Could not insert two items with with the same partition- and row key.
```

The code to reproduce this issue is as follows:

```c#
CloudStorageAccount storageAccount = CloudStorageAccount.DevelopmentStorageAccount;
CloudTableClient tableClient = storageAccount.CreateCloudTableClient();
CloudTable table = tableClient.GetTableReference("demo");

table.CreateIfNotExists();

TableBatchOperation batch = new TableBatchOperation
{
    TableOperation.InsertOrReplace(new TableEntity { PartitionKey = "NBA", RowKey = "Lakers" }),
    TableOperation.InsertOrReplace(new TableEntity { PartitionKey = "NBA", RowKey = "Lakers" }),
};

table.ExecuteBatch(batch);
```

**Comment by pemari-msft** [comment]
We've made this message more clear in our 6.0.0 release -- it now reads: "Element i in the batch returned an unexpected response code." with i being the relevant index. Thanks for the feedback!

**Comment by tbithell** [comment]
Why does it throw an error to begin with?  I've got a batch operation that is filled over and over again via a loop.  Each individual entity is InsertOrMerge which shouldn't care if I put 100 entities in it with the same partition and row keys.  There will be occasions when a duplicate will happen due to improper data entry, but I'm OK with that as long as the batch runs.  Is there a way to code around this without having to dig through my batch and remove these entities?  I'm asking all this because if I wasn't batching these it'd work fine, which is a pretty bit con for batching.  I mean why not report that an entity was removed since it had bad data and run the rest of the batch?

**Comment by golfalot** [comment]
This delightfully unhelpful error `Microsoft.Azure.Cosmos.Table.StorageException: Element 0 in the batch returned an unexpected response code` can also occur if you have a [disallowed character](https://docs.microsoft.com/en-us/rest/api/storageservices/Understanding-the-Table-Service-Data-Model?redirectedfrom=MSDN#characters-disallowed-in-key-fields) in `PartionKey `or `RowKey`


@tbithell I investigated the problem by catching `StorageException `and within that iterate over `TableOperation.InsertOrReplace` which still returned a rather useless `400 BadRequest` My problem item was a forward slash in `RowKey`.

**Comment by amnguye** [comment]
Table support has moved to the CosmosDB NuGet package. Please follow up there.

https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table
