### ISSUE TITLE
Microsoft.WindowsAzure.Storage namespace causes massive conflicts (ambiguous references)

### ISSUE THREAD

**Issue by danrozenberg** [Azure/azure-storage-net#842]
### Which service(blob, file, queue, table) does this issue concern?
Blobs, but it applies to all.

### Which version of the SDK was used?
`9.4.2` and `9.3.1`

### Which platform are you using? (ex: .NET Core 2.1)
netcoreapp2.1

### What problem was encountered?
We have a project that we want to consume the latest `Microsoft.Azure.Storage.Blob 9.4` nugets. However, since this project has a dependency that consumes the `Microsoft.WindowsAzure.Storage 9.3` nugets, we are unable to use types from the `Microsoft.WindowsAzure.Storage` namespace as those are now ambiguous between the `Microsoft.WindowsAzure.Storage` and `Microsoft.Azure.Storage.Blob` nugets...

This would normally be solved by using `extern alias`, but that feature does not seem to be working correctly in .net core and requires workarounds...

But the worse part is that we have a complex dependency chain, which, even with `extern alias`, creates a massive chain effect where every project needs to do its own `extern aliasing`.

### How can we reproduce the problem in the simplest way?
Create project `A` and have it consume `Microsoft.WindowsAzure.Storage 9.3` 
Create project `B` and have it consume `Microsoft.Azure.Storage.Blob 9.4`. Also add a reference to project `A`.

In project `B`, try to use blob types, such as `CloudBlobClient`. You will get the CS0433 error.
Try to extern alias and you'll see it's not trivial

### Have you found a mitigation/solution?
No; complex dependency chains make migration to 9.4 hard. This is specially true when we do not control "upstream" projects.

Ideally, all types from the  `Microsoft.Azure.Storage.Blob 9.4` nuget would exist in the `Microsoft.Azure.Storage.Blob` namespace.

**Comment by ahumeniy** [comment]
I'm having the same problem, but with an Azure Functions project using .NET Core 2.1. There is no reference to Azure Storage added, but there appears to be one and if you install the latest Azure Storage library from Nuget you get the following error:

    error CS0433: The type 'CloudStorageAccount' exists in both 'Microsoft.Azure.Storage.Common, Version=9.4.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.WindowsAzure.Storage, Version=9.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by kfarmer-msft** [comment]
@danrozenberg With the exception of service-specific types in Microsoft.WindowsAzure.Storage.Core.*, all types in the 9.4 packages exist in the same service-specific namespace.  What you're seeing is a conflict between the shared Common nuget package and the old monolithic package.  We agree that extern aliasing isn't pretty, but it is the only thing we can recommend if moving to 9.4 is a requirement, and your other dependencies are unable to make that change (eg, due to a dependency on the Table service).

Background: When we came to the point of making the transition, we were prepared to change the namespaces utterly (as seen, I think, in the old preview).  In the interests, at the time, of allowing existing code to compile without changing namespaces, we kept the old namespace.  On reflection, this probably created more friction than it eased, but 9.4.x doesn't really add much to 9.3.2.  Unless you really need to, you can opt to not move forward at this time.  

There will be a future release that switches the new namespace.  We do not have an ETA for that change.
