### ISSUE TITLE
NamingValidator throwing exceptions instead of returning a result

### ISSUE THREAD

**Issue by mortizzle** [Azure/azure-storage-net#856]
### Which service(blob, file, queue, table) does this issue concern?
The NameValidator class in Microsoft.WindowsAzure.Storage namespace

### What problem was encountered?
If I use a validator class I expect some kind of validation result, not to have to catch exceptions. This seems like a bit of an anti pattern.

### How can we reproduce the problem in the simplest way?
Call any method on NamingValidator passing in empty or invalid strings.

It's tough trying to educate starting programmers on proper exception use when they see patterns like this from big players. 

Happy to do the legwork of making changes if I can get some guidance on how to achieve this in a non-breaking change manner.

**Comment by kfarmer-msft** [comment]
Yeah, I agree.  The good news is that don't think it's actually referenced anywhere except in tests.  The bad news is that it is in fact a public API, otherwise I'd remove it outright (I prefer to not second-guess the server on many things -- the set of allowed characters in names being among them).

As priorities go, this is going to be very low compared to anything else on our backlog.  You might turn it into a great exercise of refactoring these into bool-returning methods, while retaining the existing, throwing, methods for backward compatibility.

**Comment by pemari-msft** [comment]
Just to clarify, these methods should not be used on the hot path of any customer application. Given they’re using regular expressions, this will affect the performance of the app. They’re provided for convenience of understanding, rather than as a tool within production code (hence the non-bool result).
