### ISSUE TITLE
Exception thrown and reported on every call to CreateIfNotExists()

### ISSUE THREAD

**Issue by ryanshripat** [Azure/azure-storage-net#862]
Once a table exists, every subsequent call to CreateIfNotExists() generates an HTTP Exception (409) which is reported in App Insights as a Failure. What's the best practice for avoiding this? I'd like to reduce the noise on my Application Insights logs.

https://github.com/Azure/azure-storage-net/blob/e22fe9175f7335dc854f8e68c30eda8244cdef69/Lib/ClassLibraryCommon/Blob/CloudBlobContainer.cs#L221

**Comment by alanlima** [comment]
Hi @ryanshripat 

I just worked on this same issue with my project.
I stopped to use `CreateIfNotExists()` and start to call `Exists()` before `Create()`. Also, I store, in a static list, the containers which I already checked so the following request to not need to check again.

PS: I am quite surprised with the way that this method works, it attempts to create the container first before check if it exists or not; that's why the AppInsight is logging the error.

I hope that I helped ;)

**Comment by seanmcc-msft** [comment]
This is by design, to allow CreateIfNotExists() to be an atomic operation.

**Comment by kfarmer-msft** [comment]
@alanlima, @ryanshripat -- Some more detail:

Once data hits the wire, it is already obsolete: Nothing prevents that container from being deleted (or, alternatively) created once the server comes up with an answer to your Exists() request and starts transmitting it to you.  Calling Exists() before Create() merely to avoid a 409 that's caught internally doesn't actually protect you in the general case -- it simply changes the window of opportunity to invalidate the Exists() while adding another network call.  The approach taken in the SDK of simply calling Create(), and swallowing any exception from the server allows the Create operation to complete in a single call. 

You'll occasionally see this pattern in other libraries.

**Comment by smariussorin** [comment]
@kfarmer-msft Thanks for the proper explanation, a simple 'This is by design' is not a valid answer when it generates errors in the insights and you lose 3 hours to check and test. Maybe an warning should be set on the method so the users know about it generating insights logs.
