### ISSUE TITLE
Unable to access premium performance blockblobstorage account using Microsoft.Azure.Storage.Blob package

### ISSUE THREAD

**Issue by Expecho** [Azure/azure-storage-net#884]
When using the nuget Microsoft.Azure.Storage.Blob, version 10.0.1 on .Net Framework v4.6.2 I cannot perform operations on a newly created storage account of type blockblobstorage with premium performance ([link](https://azure.microsoft.com/en-us/blog/azure-premium-block-blob-storage-is-now-generally-available/)).  

The code is as follows:

	var connectionString = "DefaultEndpointsProtocol=xxx";
	var storageAccount = CloudStorageAccount.Parse(connectionString);
            var blobClient = storageAccount.CreateCloudBlobClient();

        var    _container = blobClient.GetContainerReference("test");
	_container.CreateIfNotExists();

The code fails at `_container.CreateIfNotExists();` with the StorageException "The value for one of the HTTP headers is not in the correct format."

The same code with the same connection string works flawless when using the WindowsAzure.Storage nuget package.

**Comment by TravisTroyer** [comment]
I just upgraded from Microsoft.Azure.Storage.Blob 9.4.2 to Microsoft.Azure.Storage.Blob 10.0.1, and I'm having the same issue.

I can still connect to standard blob storage containers from the new library, and still connect to my premium container from the older library, but new + premium = exception.

It seems like the premium blob service may not support API Version 2018-11-09, because it's specifically complaining about the x-ms-version header.

**Comment by TravisTroyer** [comment]
I've been trying this throughout the day to see whether anything changes, and just now I successfully used 10.0.1 against a premium storage container.  I'm guessing the service API has been updated?

**Comment by Expecho** [comment]
> I've been trying this throughout the day to see whether anything changes, and just now I successfully used 10.0.1 against a premium storage container.  I'm guessing the service API has been updated?

This is really weard. It works again on my side as well. Oh well, glad it resolved itself :-)
