### ISSUE TITLE
BlobWriteStream mixing ASYNC code in non-ASYNC context

### ISSUE THREAD

**Issue by AgLeaderMTR** [Azure/azure-storage-net#906]
### Which service(blob, file, queue, table) does this issue concern?
Blob - specifically BlobWriteStream.cs:

public override void Write(byte[] buffer, int offset, int count)
    {
      this.WriteAsync(buffer, offset, count, CancellationToken.None).GetAwaiter().GetResult();
    }

### Which version of the SDK was used?

10.0.3

### Which platform are you using? (ex: .NET Core 2.1)
.NET Framework 4.6.2 with ASP.NET MVC 

### What problem was encountered?

We recently upgraded from the Microsoft.WindowsAzure.Storage library v8 to the 10.0.3 version and existing code exercised from the web application started to intermittently hang.  Determined from following our code to into the storage library code there appears to be a mix of Async and non-Async methods which is not allowed in a MVC web application because that is known to create occasional dead-locks with the synchronization context.

### How can we reproduce the problem in the simplest way?

Create a MVC Web application with an ASYNC controller method invoke CloudBlockBlob.UploadFromStream.  I don't think a prior version of the library when we originally built our code (cirra 2013, has ASYNC methods).  

If you dig into CloudBlockBlob.UploadFromStream, you eventually get to 
internal CloudBlockBlob.UploadFromStreamHelper, which leads you to
stream2.WriteToSync<NullType> which leads you to StreamExtensions.WriteToSync<T>
which leads you to: toStream.Write(numArray, 0, count); 

From what I can tell, the stream passed into this call is the fore mentioned BlobWriteStream.cs
which it's write method is:
 this.WriteAsync(buffer, offset, count, CancellationToken.None).GetAwaiter().GetResult();
which then is inadvertently mixing ASYNC code with a non-ASYNC execution context.

### Have you found a mitigation/solution?
We have not decided yet.  We might revert back to the storage library 8 in the meantime, otherwise we'd need to convert all our code used in the ASYNC context which was calling old non-ASYNC methods to use ASYNC.

**Comment by AgLeaderMTR** [comment]
After some additional digging into the Blob source code my co-worker found this post: https://github.com/Azure/azure-storage-net/issues/367.  Our understanding of that post is that the updated blob client code uses an SYNC-over-ASYNC pattern which I'm pretty sure is the cause of our perceived dead-locking at the ASP.NET MVC controller layer when the controller method is ASYNC.  It is also how I understand the code that is eventually invoked from SYNC methods (CommonUtility.RunWithoutSynchronizationContext).  We also understood from that post the intention was that eventually all SYNC methods would be removed.

Confirmation of our understanding would be appreciated.  We are presently proceeding down the path to stop using any SYNC method calls into the blob library.

**Comment by kfarmer-msft** [comment]
@AgLeaderMTR :  Moving to pure async is the appropriate thing to do.  As we all are aware, sync-over-async is a minefield which has caught many projects (including this one) a number of times.

Unfortunately, there are no sync Send methods on the HTTP client, and the existing codebase is difficult to fix these sort of issues in.  While an ideal world would involve everyone moving to pure async, that has proven to be an unrealistic goal.  So this issue is being addressed more directly in the new v12 preview announced a few days ago, with a different architecture and a goal of a pure-sync offering for those customers that require it, including a more deeply-sync implementation of the HTTP client's Send method being made available.

I'd invite anyone wishing to check it out to do so, and please to do so in those environments that tend to trigger these issues, such as ASP.NET, WPF, and the like. You'll find the blobs preview at https://www.nuget.org/packages/Azure.Storage.Blobs.

**Comment by AgLeaderMTR** [comment]
@kfarmer-msft Thanks for the reply.  I finished upgrading 'all' of our code to use ASYNC and the dead-locking problems are no more.  We don't specifically need a SYNC only form of the library.  We are just dealing with code originally written in 2013 when WebRequest was still a thing before HttpClient took over.

**Comment by kfarmer-msft** [comment]
Glad to hear. If only more people were in the position to do the same. :)

I'd still invite you to check out the preview.  It's a much more pleasant experience developing for it (nothing like ground-up reimplementations to clean up a decade of baggage), and we'd like to know whether it's a more straightforward experience to develop *with*.
